window.ZAHRADA_DASHBOARD = {
  title: "Zahradní projekt - master dashboard",
  intro:
    "Konsolidovaná verze s kompletním výpočtem práce, deníkem 23.-30. 6., vyúčtováním se sousedy a aktuálními novinkami.",
  nav: [
    ["overview", "🏡 Přehled"],
    ["docs", "🔗 Dokumenty"],
    ["budget", "💰 Rozpočet"],
    ["work-costs", "👷 Práce"],
    ["worklog", "📒 Deník"],
    ["settlement", "🤝 Vyúčtování"],
    ["projects", "✅ Projekty"],
    ["plan", "📋 Plán"],
    ["electricity", "⚡ Elektřina"],
    ["timeline", "📅 Timeline"],
    ["missing", "⚠️ Doplnit"],
  ],
  overview: [
    {
      badge: "✅ Dokončeno",
      tone: "good",
      title: "🧱 Jižní plot",
      body: "26. 6. dokončen jižní plot bez podhrabovek.",
    },
    {
      badge: "⏳ Zbývá omítka",
      tone: "wait",
      title: "🪵 Zahradní přepažení",
      body: "WPC desky jsou nahozené. Zbývá omítnout. Fasáda: Mistral omítka silikon 1,5H TB.",
    },
    {
      badge: "50 / 50",
      tone: "split",
      title: "🤝 Společná práce",
      body: "Společná práce 23.-29. 6. celkem 23 700 Kč, podíl každé strany 11 850 Kč.",
    },
    {
      badge: "✅ 8 + 1 dnů",
      tone: "good",
      title: "👷 Práce Ivanovy party",
      body: "Celkem 8 plných pracovních dnů x 9 000 Kč + 1 snížený den x 6 000 Kč = 78 000 Kč. Dne 30. 6. vyplaceno Ivanovi 72 000 Kč, zbývá doplatit 6 000 Kč.",
    },
  ],
  documents: [
    {
      title: "🎨 Vizualizace",
      label: "Otevřít",
      href: "https://drive.google.com/drive/folders/1T8yMMrG4i_ONeV4YYDIMt_nCTC70tfVn?usp=drive_link",
    },
    {
      title: "🎥 Videoprohlídka",
      label: "Otevřít",
      href: "https://drive.google.com/drive/folders/1hPTJq9R4rC93LgFnRT1XxNm9Bq4s2qg_?usp=drive_link",
    },
    {
      title: "📐 Plány zahrady",
      label: "Otevřít",
      href: "https://drive.google.com/drive/folders/11Yka0ctc8tWe06xxajmNqD6CEx1QtDaY",
    },
    {
      title: "🧱 3D JUPITER 173 cm",
      label: "Otevřít produkt",
      href: "https://www.levne-pletivo.cz/plotovy-panel-3d-jupiter-173-cm-drat-4-mm-antracit/",
    },
    {
      title: "🚗 Driveway plot Fortamigo",
      label: "Otevřít produkt",
      href: "https://www.fortamigo.cz/sada-pro-vyrobu-hlinikoveho-plotoveho-pole-2-m-x-1-2-m--antracit-ral7016--hladky-povrch/",
    },
    {
      title: "🪵 ROJA WPC panel",
      label: "Otevřít panel",
      href: "https://www.roja.cz/zahradni-nabytek/ploty/roja-modern-plotovy-panel-wpc-180x180-cm-horizontalni-i-vertikalni-a-koncovky-teak",
    },
    {
      title: "🪵 ROJA sloupek",
      label: "Otevřít sloupek",
      href: "https://www.roja.cz/zahradni-nabytek/ploty/hlinikovy-sloupek-k-plotu-7-5x7-5x240-cm",
    },
    {
      title: "🎨 Omítka",
      body: "Mistral omítka silikon 1,5H TB.",
    },
  ],
  budget: {
    cards: [
      ["✅ Schváleno", "good", "🪵 Pergola", "207 000 Kč"],
      ["✅ Zaplaceno + dovezeno", "good", "🧱 Ploty a podhrabovky", "31 305,98 Kč"],
      ["50 / 50", "split", "🪵 Zahradní přepažení WPC", "37 669 Kč"],
      ["50 / 50", "split", "🚗 Driveway plotové pole", "14 721 Kč"],
      ["50 / 50", "split", "🧱 OBI sdílený materiál", "12 964 Kč", "Beton, ztracené bednění, roxor a klíny. Podíl každé strany 6 482 Kč."],
      ["✅ Uhrazeno", "good", "🔌 OBI nesdílený materiál", "927 Kč", "Chránička, armovací tkanina a lepidlo. 100 % náš náklad."],
      ["✅ Položeno", "good", "🪨 Dlažba 14 m²", "9 800 Kč", "Zakoupeno, zaplaceno a položeno. Součástí objednávky byla i menší část dlažby určená pro sousedy; náklad zůstává 100 % na naší straně."],
      ["✅ Uhrazeno", "good", "🧱 Ivan - cement", "5 644 Kč"],
      ["✅ Evidováno", "good", "👷 Práce Ivanovy party", "78 000 Kč", "8 plných dnů + 1 snížený den. Den 29. 6. má sazbu 6 000 Kč, protože pracovali pouze Ivan a Tatíno."],
      ["✅ Uhrazeno", "good", "💸 Částečné vyrovnání Ivanovi", "72 000 Kč", "Vyplaceno 30. 6. 2026 proti evidované práci Ivanovy party. Zbývá doplatit 6 000 Kč."],
      ["✅ Uhrazeno", "good", "🧱 Zábradlí", "80 109,12 Kč"],
      ["⏳ Odhad", "wait", "🪨 Dlažba pod zahradní domek", "18 200 Kč", "Plánovaná dlažba cca 26 m² pro budoucí zahradní domek."],
      ["⏳ Plánováno", "wait", "🪞 Zrcadla", "⏳ doplnit", "Výšku zrcadel musí odsouhlasit Lucie."],
      ["⏳ Plánováno", "wait", "🧱 Tapety", "⏳ doplnit"],
    ],
    rows: [
      ["Pergola", "207 000 Kč", "✅ schváleno"],
      ["Ploty a podhrabovky", "31 305,98 Kč", "✅ zaplaceno a dovezeno"],
      ["Zahradní přepažení WPC", "37 669 Kč", "✅ objednáno, sdílené"],
      ["Driveway plotové pole", "14 721 Kč", "✅ uhrazeno námi, sdílené"],
      ["OBI sdílený materiál k přepažení", "12 964 Kč", "✅ uhrazeno námi, sdílené 50 / 50"],
      ["OBI nesdílený materiál", "927 Kč", "✅ uhrazeno námi, mimo vyúčtování s Loffelmanovými"],
      ["Dlažba 14 m²", "9 800 Kč", "✅ zakoupeno, zaplaceno a položeno; menší část objednávky byla určena pro sousedy, náklad zůstává náš"],
      ["Ivan - cement a materiál", "5 644 Kč", "✅ uhrazeno 20. 6."],
      ["Práce Ivanovy party", "78 000 Kč", "✅ 8 plných dnů + 1 snížený den; částečně uhrazeno 72 000 Kč dne 30. 6."],
      ["Částečné vyrovnání Ivanovi", "72 000 Kč", "✅ uhrazeno 30. 6. 2026, platba proti závazku práce"],
      ["Zábradlí", "80 109,12 Kč", "✅ dokončeno, namontováno a uhrazeno - 100 % náš náklad"],
      ["Dlažba pod zahradní domek cca 26 m²", "18 200 Kč", "⏳ odhad"],
      ["Zrcadla", "⏳ doplnit", "Plánováno"],
      ["Tapety", "⏳ doplnit", "Plánováno"],
    ],
    totals: [
      ["Nákladový součet včetně práce a odhadu", "496 340,10 Kč"],
      ["Potvrzené / objednané bez odhadu dlažby", "478 140,10 Kč"],
      ["Z vyúčtované práce uhrazeno Ivanovi", "72 000 Kč"],
      ["Zbývá doplatit Ivanovi", "6 000 Kč"],
    ],
  },
  workCosts: {
    note:
      "Standardní denní sazba: 9 000 Kč / den. Evidováno 8 plných pracovních dnů a 1 snížený den 29. 6. se sazbou 6 000 Kč, protože pracovali pouze Ivan a Tatíno.",
    cards: [
      ["Celkem", "good", "Veškerá práce", "78 000 Kč"],
      ["Společný projekt", "split", "Práce k dělení", "23 700 Kč"],
      ["Náš podíl", "split", "Podíl na sdílené práci", "11 850 Kč"],
      ["Podíl sousedů", "split", "Loffelmanovi", "11 850 Kč"],
      ["Náš projekt", "good", "Samostatná práce", "54 300 Kč"],
      ["Reálně naše", "good", "Náš náklad práce", "66 150 Kč"],
    ],
    headers: ["Datum", "Celkem den", "Společný projekt", "Náš projekt", "Náš podíl společně", "Podíl sousedů"],
    rows: [
      ["17. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč"],
      ["18. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč"],
      ["19. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč"],
      ["22. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč"],
      ["23. 6.", "9 000 Kč", "4 500 Kč", "4 500 Kč", "2 250 Kč", "2 250 Kč"],
      ["24. 6.", "9 000 Kč", "6 750 Kč", "2 250 Kč", "3 375 Kč", "3 375 Kč"],
      ["25. 6.", "9 000 Kč", "6 750 Kč", "2 250 Kč", "3 375 Kč", "3 375 Kč"],
      ["26. 6.", "9 000 Kč", "4 500 Kč", "4 500 Kč", "2 250 Kč", "2 250 Kč"],
      ["29. 6.", "6 000 Kč", "1 200 Kč", "4 800 Kč", "600 Kč", "600 Kč"],
    ],
    total: ["Součet", "78 000 Kč", "23 700 Kč", "54 300 Kč", "11 850 Kč", "11 850 Kč"],
  },
  worklog: {
    monthLabel: "Červen 2026",
    weekdays: ["Po", "Út", "St", "Čt", "Pá", "So", "Ne"],
    legend: [
      ["🟩", "Náš projekt"],
      ["🟦", "Společný projekt"],
      ["🟧", "Kombinovaný den"],
      ["💸", "Platba / vyrovnání"],
      ["⬜", "Nepracovalo se"],
    ],
    days: [
      { day: 1, type: "off", title: "Nepracovalo se" },
      { day: 2, type: "off", title: "Nepracovalo se" },
      { day: 3, type: "off", title: "Nepracovalo se" },
      { day: 4, type: "off", title: "Nepracovalo se" },
      { day: 5, type: "off", title: "Nepracovalo se" },
      { day: 6, type: "off", title: "Nepracovalo se" },
      { day: 7, type: "off", title: "Nepracovalo se" },
      { day: 8, type: "off", title: "Nepracovalo se" },
      { day: 9, type: "off", title: "Nepracovalo se" },
      { day: 10, type: "off", title: "Nepracovalo se" },
      { day: 11, type: "off", title: "Nepracovalo se" },
      { day: 12, type: "off", title: "Nepracovalo se" },
      { day: 13, type: "off", title: "Nepracovalo se" },
      { day: 14, type: "off", title: "Nepracovalo se" },
      { day: 15, type: "off", title: "Nepracovalo se" },
      { day: 16, type: "off", title: "Nepracovalo se" },
      {
        day: 17,
        type: "own",
        title: "Start prací",
        short: "Start",
        tooltip: "17.6. Start prací / Ivanova parta / 9 000 Kč",
        detail: {
          date: "17. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Start prací na zahradě"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Ivanova parta začala pracovat. Sazba dne 9 000 Kč.",
        },
      },
      {
        day: 18,
        type: "own",
        title: "Práce pokračují",
        short: "Práce",
        tooltip: "18.6. Práce pokračují / Ivanova parta / 9 000 Kč",
        detail: {
          date: "18. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Práce pokračují"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Celý den je vedený jako náš samostatný projekt.",
        },
      },
      {
        day: 19,
        type: "own",
        title: "Práce pokračují",
        short: "Práce",
        tooltip: "19.6. Práce pokračují / Ivanova parta / 9 000 Kč",
        detail: {
          date: "19. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Práce pokračují"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Celý den je vedený jako náš samostatný projekt.",
        },
      },
      { day: 20, type: "off", title: "Nepracovalo se" },
      { day: 21, type: "off", title: "Nepracovalo se" },
      {
        day: 22,
        type: "own",
        title: "Práce pokračují",
        short: "Práce",
        tooltip: "22.6. Práce pokračují / Ivanova parta / 9 000 Kč",
        detail: {
          date: "22. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Práce pokračují"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Celý den je vedený jako náš samostatný projekt.",
        },
      },
      {
        day: 23,
        type: "mixed",
        title: "Společný západní plot",
        short: "Plot",
        tooltip: "23.6. Společný západní plot / 50 % společné / 9 000 Kč",
        detail: {
          date: "23. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Společný západní plot", "Práce od 10:00 na hranici s Loffelmanovými"],
          finance: { total: 9000, ownPercent: 50, sharedPercent: 50, ownAmount: 4500, sharedAmount: 4500, ourSharedShare: 2250, neighborSharedShare: 2250, ourCost: 6750 },
          projects: ["🪵 Zahradní přepažení", "🏡 Náš zahradní projekt"],
          notes: "Sdílená práce cca 50 % dne.",
        },
      },
      {
        day: 24,
        type: "mixed",
        title: "Ztracené bednění",
        short: "Bednění",
        tooltip: "24.6. Ztracené bednění / 75 % společné / 9 000 Kč",
        detail: {
          date: "24. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Nákup, měření a zasazení ztraceného bednění", "Stržení jižního plotu"],
          finance: { total: 9000, ownPercent: 25, sharedPercent: 75, ownAmount: 2250, sharedAmount: 6750, ourSharedShare: 3375, neighborSharedShare: 3375, ourCost: 5625 },
          projects: ["🪵 Zahradní přepažení", "🧱 Ploty a zeď"],
          notes: "Cca 75 % dne společný projekt, 25 % náš samostatný projekt.",
        },
      },
      {
        day: 25,
        type: "mixed",
        title: "ROJA + betonáž",
        short: "Betonáž",
        tooltip: "25.6. ROJA + betonáž / 75 % společné / 9 000 Kč",
        detail: {
          date: "25. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Dorazily ROJA WPC desky a sloupky", "Betonáž"],
          finance: { total: 9000, ownPercent: 25, sharedPercent: 75, ownAmount: 2250, sharedAmount: 6750, ourSharedShare: 3375, neighborSharedShare: 3375, ourCost: 5625 },
          projects: ["🪵 Zahradní přepažení", "🧱 Ploty a zeď"],
          notes: "Cca 75 % dne společný projekt.",
        },
      },
      {
        day: 26,
        type: "mixed",
        title: "Jižní plot + WPC",
        short: "WPC",
        tooltip: "26.6. Jižní plot + WPC / 50 % společné / 9 000 Kč",
        detail: {
          date: "26. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Jižní plot dokončen bez podhrabovek", "WPC desky nahozeny"],
          finance: { total: 9000, ownPercent: 50, sharedPercent: 50, ownAmount: 4500, sharedAmount: 4500, ourSharedShare: 2250, neighborSharedShare: 2250, ourCost: 6750 },
          projects: ["🪵 Zahradní přepažení", "🧱 Ploty a zeď"],
          notes: "Zbývá omítnout. Použitá fasáda: Mistral omítka silikon 1,5H TB.",
        },
      },
      { day: 27, type: "off", title: "Nepracovalo se" },
      {
        day: 28,
        type: "off",
        title: "Zábradlí dokončeno a vyfakturováno",
        short: "Zábradlí",
        tooltip: "28.6. Zábradlí dokončeno a vyfakturováno / bez práce Ivanovy party",
        detail: {
          date: "28. 6. 2026",
          workers: [],
          done: ["Zábradlí dokončeno", "Faktura č. 26062801 zaevidována"],
          projects: ["🧱 Zábradlí"],
          notes: "Faktura od Petr Sedláček / AKTO na 80 109,12 Kč. Jde o 100 % soukromý náklad mimo vyúčtování s Loffelmanovými.",
        },
      },
      {
        day: 29,
        type: "mixed",
        title: "Nátěr perlinky na zídku",
        short: "Perlinka",
        tooltip: "29.6. Perlinka / 2 pracovníci / 6 000 Kč",
        detail: {
          date: "29. 6. 2026",
          workers: ["Ivan", "Tatíno"],
          done: ["Perlinka", "Zídka"],
          finance: { total: 6000, ownPercent: 80, sharedPercent: 20, ownAmount: 4800, sharedAmount: 1200, ourSharedShare: 600, neighborSharedShare: 600, ourCost: 5400 },
          projects: ["🪵 Zahradní přepažení"],
          notes: "Dělal se nátěr perlinky na zídku. Pracovali pouze Ivan a Tatíno, proto snížená sazba dne 6 000 Kč. 20 % času bylo na společném projektu a 80 % na našem samostatném projektu.",
        },
      },
      {
        day: 30,
        type: "payment",
        selected: true,
        title: "Částečné vyrovnání s Ivanem",
        short: "Vyrovnání",
        tooltip: "30.6. Částečné vyrovnání s Ivanem / vyplaceno 72 000 Kč",
        detail: {
          date: "30. 6. 2026",
          workers: [],
          done: ["Proběhlo částečné finanční vyrovnání s Ivanem", "Vyplaceno 72 000 Kč"],
          finance: { total: 72000, ourCost: 72000 },
          projects: ["👷 Práce Ivanovy party"],
          notes: "Platba je vedena proti už evidované práci Ivanovy party v celkové hodnotě 78 000 Kč. Historie práce zůstává zachovaná, po částečném vyrovnání zbývá doplatit 6 000 Kč.",
        },
      },
    ],
  },
  settlement: {
    intro:
      "Průběžné vyúčtování položek, které se budou dělit rovným dílem mezi nás a Lofflemanovy. Jméno Loffleman označuje sousedy; projektová položka se jmenuje Zahradní přepažení.",
    cards: [
      ["Materiál 50 / 50", "split", "🪵 WPC desky + sloupky + příslušenství", "37 669 Kč", "Náš podíl: 18 834,50 Kč\nPodíl Lofflemanových: 18 834,50 Kč"],
      ["Materiál 50 / 50", "split", "🚗 Hliníkové plotové pole driveway", "14 721 Kč", "Náš podíl: 7 360,50 Kč\nPodíl Lofflemanových: 7 360,50 Kč"],
      ["Materiál 50 / 50", "split", "🧱 OBI materiál k přepažení", "12 964 Kč", "Náš podíl: 6 482 Kč\nPodíl Lofflemanových: 6 482 Kč"],
      ["Práce 50 / 50", "split", "👷 Sdílená práce 23.-29. 6.", "23 700 Kč", "Náš podíl: 11 850 Kč\nPodíl Lofflemanových: 11 850 Kč"],
      ["Známý základ", "good", "💰 Aktuálně známé sdílené náklady", "89 054 Kč", "Náš podíl: 44 527 Kč\nPodíl Lofflemanových: 44 527 Kč"],
    ],
    headers: ["Položka", "Celkem", "Dělení", "Náš podíl", "Podíl Lofflemanových", "Stav"],
    rows: [
      ["🪵 WPC desky + sloupky + příslušenství", "37 669 Kč", "50 / 50", "18 834,50 Kč", "18 834,50 Kč", "✅ zaplaceno / objednáno"],
      ["🚗 Hliníkové plotové pole driveway", "14 721 Kč", "50 / 50", "7 360,50 Kč", "7 360,50 Kč", "✅ zaplaceno námi"],
      ["🧱 OBI materiál k přepažení - účtenky ve várkách", "12 964 Kč", "50 / 50", "6 482 Kč", "6 482 Kč", "✅ zaplaceno námi"],
      ["👷 Práce 23. 6. - sdílená část 50 % dne", "4 500 Kč", "50 / 50", "2 250 Kč", "2 250 Kč", "✅ zaevidováno"],
      ["👷 Práce 24. 6. - sdílená část 75 % dne", "6 750 Kč", "50 / 50", "3 375 Kč", "3 375 Kč", "✅ zaevidováno"],
      ["👷 Práce 25. 6. - sdílená část 75 % dne", "6 750 Kč", "50 / 50", "3 375 Kč", "3 375 Kč", "✅ zaevidováno"],
      ["👷 Práce 26. 6. - sdílená část 50 % dne", "4 500 Kč", "50 / 50", "2 250 Kč", "2 250 Kč", "✅ zaevidováno"],
      ["👷 Práce 29. 6. - sdílená část 20 % dne", "1 200 Kč", "50 / 50", "600 Kč", "600 Kč", "✅ zaevidováno"],
      ["🎨 Fasáda - Mistral omítka silikon 1,5H TB", "⏳ doplnit", "50 / 50", "⏳ doplnit", "⏳ doplnit", "čeká vyúčtování"],
      ["🔩 Spojovací materiál", "⏳ doplnit", "50 / 50", "⏳ doplnit", "⏳ doplnit", "průběžně"],
      ["🪨 Dlažba u společné zídky", "⏳ spočítat", "50 / 50", "⏳ spočítat", "⏳ spočítat", "čeká zaměření"],
      ["👷 Pokládka dlažby", "⏳ spočítat", "50 / 50", "⏳ spočítat", "⏳ spočítat", "čeká"],
    ],
    total: ["Známý společný základ", "89 054 Kč", "", "44 527 Kč", "44 527 Kč", "bez položek TBD"],
    breakdown: [
      ["Materiál", "split", "📦 Materiál známý", "65 354 Kč", "Náš podíl: 32 677 Kč\nPodíl Lofflemanových: 32 677 Kč"],
      ["Práce", "split", "👷 Práce známá", "23 700 Kč", "Náš podíl: 11 850 Kč\nPodíl Lofflemanových: 11 850 Kč"],
      ["Doplnit", "wait", "⏳ Otevřené položky", "", "Fasáda, spojovací materiál, dlažba a pokládka dlažby."],
    ],
  },
  projects: [
    ["🧱 Ploty a zeď", ["✅ Vybráno", "✅ Objednáno", "✅ Zaplaceno", "✅ Dovezeno", "✅ Jižní plot dokončen bez podhrabovek"], "Jižní plot hotov", "good"],
    ["🪵 Zahradní přepažení", ["✅ ROJA WPC desky a sloupky dorazily", "✅ WPC desky nahozeny", "✅ Podezdívka / ztracené bednění proběhlo", "✅ OBI účtenky za beton a bednění zaevidovány", "⏳ Zbývá omítnout", "🎨 Omítka: Mistral silikon 1,5H TB"], "Zbývá omítka", "wait"],
    ["🪵 Pergola", ["✅ Rozpočet pergoly schválen: 207 000 Kč", "✅ Patky hotové", "⏳ Čeká termín realizace", "⏳ Navazující práce budou doplněny podle realizace"], "Čeká termín", "wait"],
    ["🌳 Zahradní domek", ["⏳ Projekt plánován", "🪨 Dlažba pod zahradní domek (cca 26 m²)", "⏳ Odhad nákladu: 18 200 Kč", "⏳ Realizace bude navázaná na finální umístění domku"], "Plánováno", "wait"],
    ["⚡ Elektro", "Kornhauser bez kolize, 380 V v rozvaděči, řešit s tátou zachování 11 kW nabíjení."],
    ["🏊 Bazén", "Čeká budget a finální plán."],
    ["🧱 Zábradlí", ["✅ Realizace dokončena", "✅ Namontováno", "✅ Uhrazeno", "✅ Projekt uzavřen", "🔒 100 % soukromý náklad, mimo sdílené vyúčtování"], "Dokončeno", "good"],
    ["🪞 Zrcadla", ["⏳ Doplnit cenu", "⏳ Schválit výšku umístění", "⏳ Montáž", "Poznámka: výšku zrcadel musí odsouhlasit Lucie."], "Čeká realizace", "wait"],
    ["🧱 Tapety", ["⏳ Doplnit cenu", "⏳ Instalace"], "Čeká realizace", "wait"],
  ],
  plan: [
    {
      title: "🧱 Ploty",
      items: [
        ["ploty-vybrany", "Ploty vybrány", true],
        ["ploty-objednany", "Ploty objednány", true],
        ["ploty-zaplaceny", "Ploty zaplaceny", true],
        ["ploty-dovezeny", "Ploty a podhrabovky dovezeny", true],
        ["jizni-plot-hotov", "Jižní plot dokončen bez podhrabovek", true],
      ],
    },
    {
      title: "🪵 Zahradní přepažení",
      items: [
        ["roja-dorazila", "ROJA WPC materiál dorazil", true],
        ["wpc-nahozeny", "WPC desky nahozeny", true],
        ["ztracene-bedneni", "Ztracené bednění / podezdívka proběhla", true],
        ["omitka-mistral", "Omítnout - Mistral silikon 1,5H TB", false],
      ],
    },
    {
      title: "🤝 Vyúčtování",
      items: [
        ["prace-23-sdilena", "Práce 23. 6. sdílená 50 % dne", true],
        ["prace-24-sdilena", "Práce 24. 6. sdílená 75 % dne", true],
        ["prace-25-sdilena", "Práce 25. 6. sdílená 75 % dne", true],
        ["prace-26-sdilena", "Práce 26. 6. sdílená 50 % dne", true],
        ["prace-29-sdilena", "Práce 29. 6. sdílená 20 % dne", true],
        ["obi-uctenky-sdilene", "OBI účtenky za beton, bednění, roxor a klíny zaevidovány", true],
        ["obi-927-mimo-sdileni", "OBI účtenka 927 Kč vyjmuta ze sdíleného vyúčtování", true],
        ["spocitat-dlazbu-sousede", "Spočítat dlažbu a práci u sousedů", false],
      ],
    },
    {
      title: "🧱 Zábradlí",
      items: [
        ["zabradli-realizace", "Realizace dokončena", true],
        ["zabradli-montaz", "Zábradlí namontováno", true],
        ["zabradli-uhrazeno", "Faktura uhrazena / zařazena mezi potvrzené náklady", true],
        ["zabradli-uzavreno", "Projekt uzavřen jako 100 % náš náklad", true],
      ],
    },
    {
      title: "🌳 Zahradní domek",
      items: [
        ["domek-dlazba-plan", "Dlažba pod zahradní domek (cca 26 m²) naplánována", false],
        ["domek-dlazba-termin", "Doplnit termín realizace dlažby pod zahradní domek", false],
      ],
    },
    {
      title: "🪞 Zrcadla",
      items: [
        ["zrcadla-cena", "Doplnit cenu", false],
        ["zrcadla-vyska-lucie", "Schválit výšku umístění s Lucií", false],
        ["zrcadla-montaz", "Montáž", false],
      ],
    },
    {
      title: "🧱 Tapety",
      items: [
        ["tapety-cena", "Doplnit cenu", false],
        ["tapety-instalace", "Instalace", false],
      ],
    },
  ],
  electricity: [
    ["✅ Uzavřeno", "good", "Hlavní kabel", "Kornhauser kontaktován. Kabel vede u souseda a není v kolizi."],
    ["✅ 380 V", "good", "Rozvaděč", "V hlavním rozvaděči je 380 V."],
    ["⚠️ Riziko", "risk", "Nabíjení 11 kW", "Rozvázáním 380 V pro zahradu můžeme přijít o 11 kW nabíjení."],
    ["⏳ Úkol", "wait", "Dotáhnout tátu", "Najít řešení bez ztráty 11 kW nabíjení."],
  ],
  timeline: [
    ["✅ Hotovo", "good", "17. 6. 2026", "Start prací Ivanovy party"],
    ["✅ Hotovo", "good", "26. 6. 2026", "Jižní plot dokončen bez podhrabovek, WPC desky nahozeny"],
    ["✅ Hotovo", "good", "28. 6. 2026", "Zábradlí dokončeno, namontováno a vyfakturováno"],
    ["✅ Hotovo", "good", "29. 6. 2026", "Nátěr perlinky na zídku, snížený pracovní den 6 000 Kč"],
    ["✅ Uhrazeno", "good", "30. 6. 2026", "💸 Částečné vyrovnání s Ivanem - vyplaceno 72 000 Kč"],
    ["⏳ Plánováno", "wait", "Doplnit", "Dlažba pod zahradní domek cca 26 m²"],
    ["⏳ Čeká", "wait", "Doplnit", "Zrcadla - cena, výška odsouhlasená Lucií a montáž"],
    ["⏳ Čeká", "wait", "Doplnit", "Tapety - cena a instalace"],
    ["⏳ Čeká", "wait", "Doplnit", "Omítka zahradního přepažení"],
    ["⏳ Čeká", "wait", "Doplnit", "Pergola - termín realizace"],
    ["⚠️ Řešit", "risk", "Doplnit", "Elektro bez ztráty 11 kW nabíjení"],
  ],
  missing: [
    "Termín realizace pergoly.",
    "Podpis sousedky k výměně plotu a podhrabovek.",
    "Táta: návrh elektro řešení bez ztráty 11 kW nabíjení.",
    "Doplnit termín realizace dlažby pod zahradní domek cca 26 m².",
    "Kluci: spočítat dlažbu a práci pro sousedy.",
    "Doúčtovat fasádu, spojovací materiál a případnou navazující práci k zahradnímu přepažení.",
    "Dokončit omítku zahradního přepažení - Mistral silikon 1,5H TB.",
    "Zrcadla: doplnit cenu a nechat Lucií odsouhlasit výšku umístění.",
    "Tapety: doplnit cenu a termín instalace.",
  ],
};
