window.ZAHRADA_DASHBOARD = {
  title: "Zahradní projekt - master dashboard",
  intro:
    "Konsolidovaná verze s kompletním výpočtem práce, deníkem 23. 6.-15. 7., vyúčtováním se sousedy a aktuálními novinkami.",
  nav: [
    ["overview", "🏡 Přehled"],
    ["recent", "🆕 Změny"],
    ["docs", "🔗 Dokumenty"],
    ["finance", "💰 Finance"],
    ["worklog", "📒 Deník"],
    ["projects", "✅ Projekty"],
    ["plan", "📋 Plán"],
    ["electricity", "⚡ Elektřina"],
    ["timeline", "📅 Timeline"],
    ["missing", "⚠️ Doplnit"],
  ],
  finance: {
    overview: [
      {
        tone: "good",
        title: "💰 Celková investice",
        body: "Kolik celý projekt stojí / bude stát?",
        metrics: [
          ["Potvrzené / objednané", "589 730,10 Kč"],
          ["Včetně práce a odhadů", "607 930,10 Kč"],
          ["Plánované / odhadované", "18 200 Kč"],
          ["Rozdíl od potvrzeného", "18 200 Kč"],
        ],
      },
      {
        tone: "wait",
        title: "💸 Cashflow",
        body: "Kolik peněz už odešlo a co ještě čeká na platbu?",
        metrics: [
          ["Zaplaceno", "311 048,10 Kč"],
          ["Čeká na úhradu", "76 824 Kč"],
          ["Proplaceno Ivanovi", "72 000 Kč"],
          ["Otevřené závazky", "76 824 Kč"],
        ],
      },
      {
        tone: "split",
        title: "🤝 Vyúčtování s Löffelmanovými",
        body: "Kolik je společný základ a kolik má připadnout na každou stranu?",
        metrics: [
          ["Známý společný základ", "153 282 Kč"],
          ["Náš podíl", "76 641 Kč"],
          ["Podíl Löffelmanových", "76 641 Kč"],
          ["100 % Löffelmanovi", "2 900 Kč"],
          ["Materiál / práce", "85 707 Kč / 67 575 Kč"],
        ],
      },
      {
        tone: "wait",
        title: "💸 K úhradě od Löffelmanových",
        body: "Kolik peněz nám mají Löffelmanovi poslat zpět?",
        metrics: [
          ["Zbývá zaplatit nám", "79 541 Kč"],
          ["Podíl na 50 / 50", "76 641 Kč"],
          ["100 % jejich náklad", "2 900 Kč"],
          ["Uhrazeno Löffelmanovými", "0 Kč"],
        ],
      },
      {
        tone: "good",
        title: "👷 Ivanova parta",
        body: "Kolik už Ivanova parta odpracovala a kolik jim ještě dlužíme?",
        metrics: [
          ["Celková práce", "143 250 Kč"],
          ["Vyplaceno", "72 000 Kč"],
          ["Zbývá doplatit", "71 250 Kč"],
          ["Dny", "13 plných + 4 dvoučlenné + 1 částečný"],
        ],
      },
    ],
    cashflow: {
      headers: ["Metrika", "Částka", "Poznámka"],
      rows: [
        ["Zaplaceno", "311 048,10 Kč", "Uhrazené platby evidované v platbách včetně částečného vyrovnání Ivanovi, podhrabových desek, tapety a sdílených účtenek T+L."],
        ["Čeká na úhradu", "76 824 Kč", "Otevřený doplatek Ivanově partě za evidovanou práci a účtenky hrazené Ivanem."],
        ["Proplaceno Ivanovi", "72 000 Kč", "Částečné vyrovnání ze dne 30. 6. 2026."],
        ["Práce k doplacení Ivanově partě", "71 250 Kč", "Zbývající závazek za evidovanou práci."],
        ["Proplacení účtenek Ivanovi", "5 574 Kč", "⏳ k proplacení; cashflow položka, projektové náklady už jsou evidované v jednotlivých účtenkách. Batch IMG_8604.JPG."],
        ["Otevřené závazky", "76 824 Kč", "Zbývající závazek vůči Ivanovi včetně práce a proplacení účtenek."],
      ],
      total: ["Celkem otevřeno", "76 824 Kč", "Práce 71 250 Kč + účtenky Ivanovi 5 574 Kč"],
    },
  },
  overview: [
    {
      badge: "✅ Dokončeno",
      tone: "good",
      title: "🧱 Jižní plot",
      body: "26. 6. dokončen jižní plot bez podhrabovek.",
    },
    {
      badge: "⏳ Zbývá omítka",
      tone: "wait",
      title: "🪵 Zahradní přepažení",
      body: "WPC desky jsou nahozené, armovací stěrka, stříšky, penetrace a navazující omítkové práce probíhaly do 15. 7. Zbývá doplnit finální stav omítky.",
    },
    {
      badge: "50 / 50",
      tone: "split",
      title: "🤝 Společná práce",
      body: "Společná práce 23. 6.-15. 7. celkem 67 575 Kč, podíl každé strany 33 787,50 Kč.",
    },
    {
      badge: "✅ 13 + 4 + část",
      tone: "good",
      title: "👷 Práce Ivanovy party",
      body: "Celkem evidovaná práce v našem a sdíleném rozpočtu je 143 250 Kč. Dne 30. 6. vyplaceno Ivanovi 72 000 Kč, zbývá doplatit 71 250 Kč.",
    },
  ],
  documents: [
    {
      title: "🎨 Vizualizace",
      label: "Otevřít",
      href: "https://drive.google.com/drive/folders/1T8yMMrG4i_ONeV4YYDIMt_nCTC70tfVn?usp=drive_link",
    },
    {
      title: "🎥 Videoprohlídka",
      label: "Otevřít",
      href: "https://drive.google.com/drive/folders/1hPTJq9R4rC93LgFnRT1XxNm9Bq4s2qg_?usp=drive_link",
    },
    {
      title: "📐 Plány zahrady",
      label: "Otevřít",
      href: "https://drive.google.com/drive/folders/11Yka0ctc8tWe06xxajmNqD6CEx1QtDaY",
    },
    {
      title: "🧱 3D JUPITER 173 cm",
      label: "Otevřít produkt",
      href: "https://www.levne-pletivo.cz/plotovy-panel-3d-jupiter-173-cm-drat-4-mm-antracit/",
    },
    {
      title: "🚗 Driveway plot Fortamigo",
      label: "Otevřít produkt",
      href: "https://www.fortamigo.cz/sada-pro-vyrobu-hlinikoveho-plotoveho-pole-2-m-x-1-2-m--antracit-ral7016--hladky-povrch/",
    },
    {
      title: "🪵 ROJA WPC panel",
      label: "Otevřít panel",
      href: "https://www.roja.cz/zahradni-nabytek/ploty/roja-modern-plotovy-panel-wpc-180x180-cm-horizontalni-i-vertikalni-a-koncovky-teak",
    },
    {
      title: "🪵 ROJA sloupek",
      label: "Otevřít sloupek",
      href: "https://www.roja.cz/zahradni-nabytek/ploty/hlinikovy-sloupek-k-plotu-7-5x7-5x240-cm",
    },
    {
      title: "🎨 Omítka",
      body: "Mistral omítka silikon 1,5H TB.",
    },
  ],
  budget: {
    cards: [
      ["✅ Schváleno", "good", "🪵 Pergola", "207 000 Kč"],
      ["✅ Zaplaceno + dovezeno", "good", "🧱 Ploty a podhrabovky", "31 305,98 Kč"],
      ["50 / 50", "split", "🪵 Zahradní přepažení WPC", "37 669 Kč"],
      ["50 / 50", "split", "🚗 Driveway plotové pole", "14 721 Kč"],
      ["50 / 50", "split", "🧱 Ztracené bednění a beton", "12 282 Kč", "Projekt: Driveway zídka. Zahrnuje sdílené OBI účtenky označené T+L z 1.-2. 7.; dvě redukce na vozík za 408 Kč byly vyřazeny z evidence. Hrazeno námi, podíl každé strany 6 141 Kč."],
      ["50 / 50", "split", "🧱 OBI sdílený materiál", "12 964 Kč", "Beton, ztracené bednění, roxor a klíny. Podíl každé strany 6 482 Kč."],
      ["50 / 50", "split", "🎨 Omítka, stříšky a lišty", "7 639 Kč", "T+L účtenky: Mistral omítka 4 356 Kč, OBI 1 039 Kč, OBI 1 404 Kč, stříšky a rohové lišty 840 Kč. Podíl každé strany 3 819,50 Kč."],
      ["50 / 50", "split", "🧾 T+L doplňková účtenka", "432 Kč", "IMG_8603.JPG. Podíl každé strany 216 Kč."],
      ["✅ Uhrazeno", "good", "🔌 OBI nesdílený materiál", "3 860 Kč", "Chránička, armovací tkanina, lepidlo, beton označený T a proplacený OBI materiál od Ivana. 100 % náš náklad."],
      ["✅ Uhrazeno + dodáno", "good", "🧱 Podhrabové desky", "1 859 Kč", "Dle účtenky Ploty Dobrý & Urbánek z 4. 7. 2026, IMG_8602.JPG. Projekt: Východní plot. 100 % náš náklad, mimo vyúčtování s Loffelmanovými."],
      ["✅ Položeno", "good", "🪨 Dlažba 14 m²", "9 800 Kč", "Zakoupeno, zaplaceno a položeno. Z toho cca 2 m² / 1 400 Kč patří Loffelmanovým a je vedeno jako 100 % jejich náklad hrazený námi."],
      ["✅ Uhrazeno", "good", "🧱 Ivan - cement", "5 644 Kč"],
      ["✅ Evidováno", "good", "👷 Práce Ivanovy party", "143 250 Kč", "Evidovaná práce v našem a sdíleném rozpočtu. Dne 15. 7. pracovala plná parta na sdílených projektech 50 / 50."],
      ["✅ Uhrazeno", "good", "💸 Částečné vyrovnání Ivanovi", "72 000 Kč", "Vyplaceno 30. 6. 2026 proti evidované práci Ivanovy party. Zbývá doplatit 71 250 Kč."],
      ["⏳ K proplacení", "wait", "💸 Proplacení účtenek Ivanovi", "5 574 Kč", "Cashflow vůči Ivanovi za účtenky v batchi IMG_8604.JPG. Nezvyšuje znovu projektové náklady."],
      ["✅ Uhrazeno", "good", "🧱 Zábradlí", "80 109,12 Kč"],
      ["⏳ Odhad", "wait", "🪨 Dlažba pod zahradní domek", "18 200 Kč", "Plánovaná dlažba cca 26 m² pro budoucí zahradní domek."],
      ["✅ Dokončeno", "good", "🪞 Zrcadla", "10 348 Kč", "Zaplaceno a dokončeno 1. 7. 2026."],
      ["✅ Uhrazeno", "good", "🪑 Konzolový stolek", "4 847 Kč", "Samostatná evidovaná položka, zatím bez přiřazení k projektu."],
      ["✅ Uhrazeno", "good", "🧱 Tapeta", "6 000 Kč", "Materiál pro projekt Tapety. Účtenka není k dispozici. 100 % náš náklad mimo vyúčtování s Loffelmanovými."],
    ],
    rows: [
      ["Pergola", "207 000 Kč", "✅ schváleno"],
      ["Ploty a podhrabovky", "31 305,98 Kč", "✅ zaplaceno a dovezeno"],
      ["Zahradní přepažení WPC", "37 669 Kč", "✅ objednáno, sdílené"],
      ["Driveway plotové pole", "14 721 Kč", "✅ uhrazeno námi, sdílené"],
      ["Ztracené bednění a beton - Driveway zídka", "12 282 Kč", "✅ uhrazeno námi, sdílené 50 / 50; T+L účtenky z 1.-2. 7., redukce na vozík vyřazeny"],
      ["OBI sdílený materiál k přepažení", "12 964 Kč", "✅ uhrazeno námi, sdílené 50 / 50"],
      ["Omítka, stříšky a lišty - Driveway + WPC", "7 639 Kč", "✅ uhrazeno námi, sdílené 50 / 50; IMG_8601.JPG"],
      ["T+L doplňková účtenka", "432 Kč", "✅ sdílené 50 / 50; IMG_8603.JPG"],
      ["OBI nesdílený materiál", "3 860 Kč", "✅ uhrazeno námi, mimo vyúčtování s Loffelmanovými; zahrnuje účtenku označenou T a proplacenou účtenku od Ivana"],
      ["Podhrabové desky", "1 859 Kč", "✅ uhrazeno a dodáno; Ploty Dobrý & Urbánek 4. 7. 2026; IMG_8602.JPG; projekt Východní plot; 100 % náš náklad mimo vyúčtování s Loffelmanovými"],
      ["Dlažba 14 m²", "9 800 Kč", "✅ zakoupeno, zaplaceno a položeno; cca 2 m² / 1 400 Kč jsou 100 % náklad Loffelmanových hrazený námi"],
      ["Ivan - cement a materiál", "5 644 Kč", "✅ uhrazeno 20. 6."],
      ["Práce Ivanovy party", "143 250 Kč", "✅ evidovaná práce v našem a sdíleném rozpočtu; 8. 7. dlažba u Loffelmanových je mimo náš i sdílený rozpočet; 15. 7. plná parta sdíleně 50 / 50; částečně uhrazeno 72 000 Kč dne 30. 6."],
      ["Částečné vyrovnání Ivanovi", "72 000 Kč", "✅ uhrazeno 30. 6. 2026, platba proti závazku práce"],
      ["Proplacení účtenek Ivanovi", "5 574 Kč", "⏳ cashflow k proplacení; batch IMG_8604.JPG; jednotlivé účtenky už jsou v nákladech započítané"],
      ["Zábradlí", "80 109,12 Kč", "✅ dokončeno, namontováno a uhrazeno - 100 % náš náklad"],
      ["Dlažba pod zahradní domek cca 26 m²", "18 200 Kč", "⏳ odhad"],
      ["Zrcadla", "10 348 Kč", "✅ zaplaceno a dokončeno 1. 7. 2026"],
      ["Konzolový stolek", "4 847 Kč", "✅ zaplaceno 1. 7. 2026, samostatná evidovaná položka"],
      ["Tapeta", "6 000 Kč", "✅ materiál pořízen / uhrazen; projekt Tapety; účtenka není k dispozici; 100 % náš náklad mimo vyúčtování s Loffelmanovými"],
    ],
    totals: [
      ["Nákladový součet včetně práce a odhadu", "607 930,10 Kč"],
      ["Potvrzené / objednané bez odhadu dlažby", "589 730,10 Kč"],
      ["Z vyúčtované práce uhrazeno Ivanovi", "72 000 Kč"],
      ["Zbývá doplatit Ivanovi", "76 824 Kč"],
    ],
  },
  recentChanges: [
    {
      date: "15. 7. 2026",
      title: "Omítky a sdílené účtenky",
      body: "Doplněny práce do 15. 7. a T+L účtenky za omítku, stříšky a navazující materiál v součtu 7 639 Kč.",
      projectIds: ["driveway-wall", "garden-partition"],
    },
    {
      date: "11. 7. 2026",
      title: "Zídky připraveny na finální omítku",
      body: "Na driveway zídce i západní zídce pod WPC byly nalepeny stříšky a provedena penetrace. Celý den je sdílený 50 / 50 s Löffelmanovými.",
      projectIds: ["driveway-wall", "garden-partition"],
    },
    {
      date: "8. 7. 2026",
      title: "Tapety dokončeny",
      body: "Dokončena ložnice. Součástí dne byla i práce výhradně pro Löffelmanovy mimo naše a sdílené náklady.",
      projectIds: ["wallpaper"],
    },
    {
      date: "7. 7. 2026",
      title: "Příprava na finální omítku",
      body: "Dokončena armovací stěrka na driveway zídce a podezdívce pod WPC jako sdílená práce s Löffelmanovými.",
      projectIds: ["driveway-wall", "garden-partition"],
    },
    {
      date: "4. 7. 2026",
      title: "Východní plot dokončen",
      body: "Po montáži panelů a podhrabových desek byl východní plot kompletně dokončen.",
      projectIds: ["east-fence"],
    },
    {
      date: "4. 7. 2026",
      title: "Tapety v dětském pokoji",
      body: "Dětský pokoj byl hotový, ložnice tehdy čekala na dodání zbývající tapety.",
      projectIds: ["wallpaper"],
    },
  ],
  projectHub: {
    columns: [
      ["waiting", "⏳ Čeká"],
      ["progress", "🔨 Probíhá"],
      ["done", "✅ Hotovo"],
    ],
    items: [
      {
        id: "pergola",
        emoji: "🪵",
        title: "Pergola",
        status: "waiting",
        summary: "Rozpočet schválen, čeká termín realizace.",
        nextStep: "Doplnit termín realizace.",
        aliases: ["pergola"],
      },
      {
        id: "pool",
        emoji: "🏊",
        title: "Bazén",
        status: "waiting",
        summary: "Čeká budget a finální plán.",
        nextStep: "Doplnit finální rozpočet.",
        aliases: ["bazén", "bazen"],
      },
      {
        id: "garden-house",
        emoji: "🌳",
        title: "Zahradní domek",
        status: "waiting",
        summary: "Plánovaná navazující etapa.",
        nextStep: "Doplnit termín dlažby pod domek.",
        aliases: ["zahradní domek", "zahradni domek", "domek"],
      },
      {
        id: "electricity",
        emoji: "⚡",
        title: "Elektro",
        status: "waiting",
        summary: "Kabel bez kolize, řeší se zachování 11 kW nabíjení.",
        nextStep: "Najít řešení s tátou.",
        aliases: ["elektro", "nabíjení", "nabijeni", "11 kW"],
      },
      {
        id: "driveway-wall",
        emoji: "🚗",
        title: "Driveway zídka",
        status: "progress",
        summary: "Stříšky, penetrace a omítkové práce probíhaly do 15. 7.",
        nextStep: "Doplnit finální stav omítky a případné pracovní sazby.",
        aliases: ["driveway", "driveway zídka", "driveway zidka"],
      },
      {
        id: "garden-partition",
        emoji: "🪵",
        title: "Zahradní přepažení",
        status: "progress",
        summary: "WPC hotové, stříšky, penetrace a omítkové práce probíhaly do 15. 7.",
        nextStep: "Doplnit finální stav omítky a případné pracovní sazby.",
        aliases: ["zahradní přepažení", "zahradni prepazeni", "wpc", "podezdívka", "podezdivka"],
      },
      {
        id: "loffelman-project",
        emoji: "🏡",
        title: "Projekt Löffelmanových",
        status: "done",
        summary: "Dlažba cca 2 m² uhrazená Trantinovými, 100 % náklad Löffelmanových.",
        nextStep: null,
        aliases: ["loffelman", "löffelman", "sousedé", "sousede", "dlažba u loffelmanových", "dlazba u loffelmanovych"],
      },
      {
        id: "wallpaper",
        emoji: "🏠",
        title: "Tapety",
        status: "done",
        summary: "Projekt Tapety dokončen 8. 7. 2026.",
        nextStep: null,
        aliases: ["tapety", "tapeta", "dětský pokoj", "detsky pokoj", "ložnice", "loznice"],
      },
      {
        id: "lighting",
        emoji: "💡",
        title: "Osvětlení",
        status: "progress",
        summary: "Více světel čeká na převzetí a montáž.",
        nextStep: "Převzít světlo do šatny a dokončit montáže.",
        aliases: ["osvětlení", "osvetleni", "světlo", "svetlo", "led"],
      },
      {
        id: "south-fence",
        emoji: "🧱",
        title: "Jižní plot",
        status: "done",
        summary: "Dokončen 26. 6. 2026 bez podhrabovek.",
        nextStep: null,
        aliases: ["jižní plot", "jizni plot"],
      },
      {
        id: "east-fence",
        emoji: "🧱",
        title: "Východní plot",
        status: "done",
        summary: "Kompletně dokončen 4. 7. 2026.",
        nextStep: null,
        aliases: ["východní plot", "vychodni plot"],
      },
      {
        id: "railing",
        emoji: "🧱",
        title: "Zábradlí",
        status: "done",
        summary: "Realizace dokončena, namontováno a uhrazeno.",
        nextStep: null,
        aliases: ["zábradlí", "zabradli"],
      },
      {
        id: "mirrors",
        emoji: "🪞",
        title: "Zrcadla",
        status: "done",
        summary: "Montáž dokončena 1. 7. 2026.",
        nextStep: null,
        aliases: ["zrcadla", "zrcadlo"],
      },
    ],
  },
  workCosts: {
    note:
      "Standardní denní sazba plné party: 9 000 Kč / den. Evidováno 13 plných dnů plné party, 4 dvoučlenné dny po 6 000 Kč a částečný den 8. 7. v našem/sdíleném rozpočtu za 2 250 Kč. Dne 15. 7. pracovala plná parta na sdílených projektech 50 / 50.",
    cards: [
      ["Celkem", "good", "Veškerá práce", "143 250 Kč"],
      ["Společný projekt", "split", "Práce k dělení", "67 575 Kč"],
      ["Náš podíl", "split", "Podíl na sdílené práci", "33 787,50 Kč"],
      ["Podíl sousedů", "split", "Loffelmanovi", "33 787,50 Kč"],
      ["Náš projekt", "good", "Samostatná práce", "75 675 Kč"],
      ["Reálně naše", "good", "Náš náklad práce", "109 462,50 Kč"],
    ],
    headers: ["Datum", "Celkem den", "Společný projekt", "Náš projekt", "Náš podíl společně", "Podíl sousedů"],
    rows: [
      ["17. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč"],
      ["18. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč"],
      ["19. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč"],
      ["22. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč"],
      ["23. 6.", "9 000 Kč", "4 500 Kč", "4 500 Kč", "2 250 Kč", "2 250 Kč"],
      ["24. 6.", "9 000 Kč", "6 750 Kč", "2 250 Kč", "3 375 Kč", "3 375 Kč"],
      ["25. 6.", "9 000 Kč", "6 750 Kč", "2 250 Kč", "3 375 Kč", "3 375 Kč"],
      ["26. 6.", "9 000 Kč", "4 500 Kč", "4 500 Kč", "2 250 Kč", "2 250 Kč"],
      ["29. 6.", "6 000 Kč", "1 200 Kč", "4 800 Kč", "600 Kč", "600 Kč"],
      ["30. 6.", "6 000 Kč", "6 000 Kč", "0 Kč", "3 000 Kč", "3 000 Kč"],
      ["1. 7.", "9 000 Kč", "6 750 Kč", "2 250 Kč", "3 375 Kč", "3 375 Kč"],
      ["2. 7.", "9 000 Kč", "9 000 Kč", "0 Kč", "4 500 Kč", "4 500 Kč"],
      ["3. 7.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč"],
      ["4. 7.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč"],
      ["7. 7.", "6 000 Kč", "6 000 Kč", "0 Kč", "3 000 Kč", "3 000 Kč"],
      ["8. 7.", "2 250 Kč", "1 125 Kč", "1 125 Kč", "562,50 Kč", "562,50 Kč"],
      ["11. 7.", "6 000 Kč", "6 000 Kč", "0 Kč", "3 000 Kč", "3 000 Kč"],
      ["15. 7.", "9 000 Kč", "9 000 Kč", "0 Kč", "4 500 Kč", "4 500 Kč"],
    ],
    total: ["Součet", "143 250 Kč", "67 575 Kč", "75 675 Kč", "33 787,50 Kč", "33 787,50 Kč"],
  },
  worklog: {
    monthLabel: "Červen / červenec 2026",
    legend: [
      ["🟩", "Náš projekt"],
      ["🟦", "Společný projekt"],
      ["🟧", "Kombinovaný den"],
      ["💸", "Platba / vyrovnání"],
      ["⬜", "Nepracovalo se"],
    ],
    days: [
      { day: 1, type: "off", title: "Nepracovalo se" },
      { day: 2, type: "off", title: "Nepracovalo se" },
      { day: 3, type: "off", title: "Nepracovalo se" },
      { day: 4, type: "off", title: "Nepracovalo se" },
      { day: 5, type: "off", title: "Nepracovalo se" },
      { day: 6, type: "off", title: "Nepracovalo se" },
      { day: 7, type: "off", title: "Nepracovalo se" },
      { day: 8, type: "off", title: "Nepracovalo se" },
      { day: 9, type: "off", title: "Nepracovalo se" },
      { day: 10, type: "off", title: "Nepracovalo se" },
      { day: 11, type: "off", title: "Nepracovalo se" },
      { day: 12, type: "off", title: "Nepracovalo se" },
      { day: 13, type: "off", title: "Nepracovalo se" },
      { day: 14, type: "off", title: "Nepracovalo se" },
      { day: 15, type: "off", title: "Nepracovalo se" },
      { day: 16, type: "off", title: "Nepracovalo se" },
      {
        day: 17,
        type: "own",
        title: "Start prací",
        short: "Start",
        tooltip: "17.6. Start prací / Ivanova parta / 9 000 Kč",
        detail: {
          date: "17. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Start prací na zahradě"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Ivanova parta začala pracovat. Sazba dne 9 000 Kč.",
        },
      },
      {
        day: 18,
        type: "own",
        title: "Práce pokračují",
        short: "Práce",
        tooltip: "18.6. Práce pokračují / Ivanova parta / 9 000 Kč",
        detail: {
          date: "18. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Práce pokračují"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Celý den je vedený jako náš samostatný projekt.",
        },
      },
      {
        day: 19,
        type: "own",
        title: "Práce pokračují",
        short: "Práce",
        tooltip: "19.6. Práce pokračují / Ivanova parta / 9 000 Kč",
        detail: {
          date: "19. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Práce pokračují"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Celý den je vedený jako náš samostatný projekt.",
        },
      },
      { day: 20, type: "off", title: "Nepracovalo se" },
      { day: 21, type: "off", title: "Nepracovalo se" },
      {
        day: 22,
        type: "own",
        title: "Práce pokračují",
        short: "Práce",
        tooltip: "22.6. Práce pokračují / Ivanova parta / 9 000 Kč",
        detail: {
          date: "22. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Práce pokračují"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Celý den je vedený jako náš samostatný projekt.",
        },
      },
      {
        day: 23,
        type: "mixed",
        title: "Společný západní plot",
        short: "Plot",
        tooltip: "23.6. Společný západní plot / 50 % společné / 9 000 Kč",
        detail: {
          date: "23. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Společný západní plot", "Práce od 10:00 na hranici s Loffelmanovými"],
          finance: { total: 9000, ownPercent: 50, sharedPercent: 50, ownAmount: 4500, sharedAmount: 4500, ourSharedShare: 2250, neighborSharedShare: 2250, ourCost: 6750 },
          projects: ["🪵 Zahradní přepažení", "🏡 Náš zahradní projekt"],
          notes: "Sdílená práce cca 50 % dne.",
        },
      },
      {
        day: 24,
        type: "mixed",
        title: "Ztracené bednění",
        short: "Bednění",
        tooltip: "24.6. Ztracené bednění / 75 % společné / 9 000 Kč",
        detail: {
          date: "24. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Nákup, měření a zasazení ztraceného bednění", "Stržení jižního plotu"],
          finance: { total: 9000, ownPercent: 25, sharedPercent: 75, ownAmount: 2250, sharedAmount: 6750, ourSharedShare: 3375, neighborSharedShare: 3375, ourCost: 5625 },
          projects: ["🪵 Zahradní přepažení", "🧱 Ploty a zeď"],
          notes: "Cca 75 % dne společný projekt, 25 % náš samostatný projekt.",
        },
      },
      {
        day: 25,
        type: "mixed",
        title: "ROJA + betonáž",
        short: "Betonáž",
        tooltip: "25.6. ROJA + betonáž / 75 % společné / 9 000 Kč",
        detail: {
          date: "25. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Dorazily ROJA WPC desky a sloupky", "Betonáž"],
          finance: { total: 9000, ownPercent: 25, sharedPercent: 75, ownAmount: 2250, sharedAmount: 6750, ourSharedShare: 3375, neighborSharedShare: 3375, ourCost: 5625 },
          projects: ["🪵 Zahradní přepažení", "🧱 Ploty a zeď"],
          notes: "Cca 75 % dne společný projekt.",
        },
      },
      {
        day: 26,
        type: "mixed",
        title: "Jižní plot + WPC",
        short: "WPC",
        tooltip: "26.6. Jižní plot + WPC / 50 % společné / 9 000 Kč",
        detail: {
          date: "26. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Jižní plot dokončen bez podhrabovek", "WPC desky nahozeny"],
          finance: { total: 9000, ownPercent: 50, sharedPercent: 50, ownAmount: 4500, sharedAmount: 4500, ourSharedShare: 2250, neighborSharedShare: 2250, ourCost: 6750 },
          projects: ["🪵 Zahradní přepažení", "🧱 Ploty a zeď"],
          notes: "Zbývá omítnout. Použitá fasáda: Mistral omítka silikon 1,5H TB.",
        },
      },
      { day: 27, type: "off", title: "Nepracovalo se" },
      {
        day: 28,
        type: "off",
        title: "Zábradlí dokončeno a vyfakturováno",
        short: "Zábradlí",
        tooltip: "28.6. Zábradlí dokončeno a vyfakturováno / bez práce Ivanovy party",
        detail: {
          date: "28. 6. 2026",
          workers: [],
          done: ["Zábradlí dokončeno", "Faktura č. 26062801 zaevidována"],
          projects: ["🧱 Zábradlí"],
          notes: "Faktura od Petr Sedláček / AKTO na 80 109,12 Kč. Jde o 100 % soukromý náklad mimo vyúčtování s Loffelmanovými.",
        },
      },
      {
        day: 29,
        type: "mixed",
        title: "Nátěr perlinky na zídku",
        short: "Perlinka",
        tooltip: "29.6. Perlinka / 2 pracovníci / 6 000 Kč",
        detail: {
          date: "29. 6. 2026",
          workers: ["Ivan", "Tatíno"],
          done: ["Perlinka", "Zídka"],
          finance: { total: 6000, ownPercent: 80, sharedPercent: 20, ownAmount: 4800, sharedAmount: 1200, ourSharedShare: 600, neighborSharedShare: 600, ourCost: 5400 },
          projects: ["🪵 Zahradní přepažení"],
          notes: "Dělal se nátěr perlinky na zídku. Pracovali pouze Ivan a Tatíno, proto snížená sazba dne 6 000 Kč. 20 % času bylo na společném projektu a 80 % na našem samostatném projektu.",
        },
      },
      {
        day: 30,
        type: "shared",
        title: "Výkop základů + vyrovnání",
        short: "🚧 Výkop driveway zídky",
        tooltip: "30.6. Výkop základů pro driveway zídku / Vasil, Tatíno, Ivan / 6 000 Kč",
        detail: {
          date: "30. 6. 2026",
          workers: ["Vasil - celý den (8 h)", "Tatíno - celý den (8 h)", "Ivan - cca 1 hodina (výpomoc)"],
          done: ["Výkop základů pro driveway zídku", "Proběhlo částečné finanční vyrovnání s Ivanem", "Vyplaceno 72 000 Kč"],
          finance: { total: 6000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 6000, ourSharedShare: 3000, neighborSharedShare: 3000, ourCost: 3000, extraRows: [["Vyrovnání Ivanovi", "72 000 Kč"]] },
          projects: ["🚗 Driveway zídka", "👷 Práce Ivanovy party"],
          notes: "Práce dne 30. 6. patří celá do společného projektu s Lofflemanovými a dělí se 50 / 50. Náklad práce: 2 osoby x 3 000 Kč = 6 000 Kč. Ve stejný den proběhlo částečné finanční vyrovnání s Ivanem ve výši 72 000 Kč.",
        },
      },
      {
        id: "2026-07-01",
        day: 1,
        label: "1.7.",
        type: "mixed",
        selected: true,
        title: "Driveway zídka + tapety",
        short: "Driveway/Tapety",
        tooltip: "1.7. Driveway zídka 75 %, tapety 25 % / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "1. 7. 2026",
          workers: ["Ivan", "Vasil", "Tatíno"],
          done: ["Driveway zídka - 75 % dne", "Tapety - 25 % dne"],
          finance: { total: 9000, ownPercent: 25, sharedPercent: 75, ownAmount: 2250, sharedAmount: 6750, ourSharedShare: 3375, neighborSharedShare: 3375, ourCost: 5625 },
          projects: ["🚗 Driveway zídka", "🏠 Tapety"],
          notes: "Pracovala plná parta: Ivan, Vasil a Tatíno. 75 % dne patří do společného projektu Driveway zídka a dělí se 50 / 50 s Lofflemanovými. 25 % dne patří do našeho projektu Tapety a do společného vyúčtování nevstupuje.",
        },
      },
      {
        id: "2026-07-02",
        day: 2,
        label: "2.7.",
        type: "shared",
        title: "Driveway zídka",
        short: "Driveway",
        tooltip: "2.7. Driveway zídka / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "2. 7. 2026",
          workers: ["Ivan", "Vasil", "Tatíno"],
          done: ["Pokračovala realizace driveway zídky", "Celý den vedený jako společný projekt 50 / 50 s Lofflemanovými"],
          finance: { total: 9000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 9000, ourSharedShare: 4500, neighborSharedShare: 4500, ourCost: 4500 },
          projects: ["🚗 Driveway zídka"],
          notes: "Pracovala plná parta: Ivan, Vasil a Tatíno. Celý den patří do společného projektu Driveway zídka a dělí se 50 / 50 s Lofflemanovými.",
        },
      },
      {
        id: "2026-07-03",
        day: 3,
        label: "3.7.",
        type: "own",
        title: "Východní plot",
        short: "Plot",
        tooltip: "3.7. Východní plot / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "3. 7. 2026",
          workers: ["Ivan", "Vasil", "Tatíno"],
          done: ["Vrty pro sloupky", "Betonování sloupků", "Erekce / osazení plotových panelů", "Montáž plotu"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourSharedShare: 0, neighborSharedShare: 0, ourCost: 9000 },
          projects: ["🧱 Východní plot", "🧱 Ploty a zeď"],
          notes: "Pracovala plná parta: Ivan, Vasil a Tatíno. Celý den se pracovalo pouze na našem projektu Východní plot. Náklad práce: 3 osoby x 3 000 Kč = 9 000 Kč. Práce na východním plotu výrazně pokročily a navazující dokončení proběhlo 4. 7. Nejde o sdílený projekt s Loffelmanovými.",
        },
      },
      {
        id: "2026-07-04",
        day: 4,
        label: "4.7.",
        type: "mixed",
        title: "Východní plot + tapety",
        short: "Plot/Tapety",
        tooltip: "4.7. Východní plot 75 %, tapety 25 % / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "4. 7. 2026",
          workers: ["Ivan", "Vasil", "Tatíno"],
          done: ["Východní plot byl kompletně dokončen", "Montáž podhrabových desek dokončena", "Tapety - dětský pokoj dokončen", "Tapety - ložnice navázala dokončením 8. 7.", "Podhrabové desky a příslušenství za 1 859 Kč uhrazeny a dodány"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourSharedShare: 0, neighborSharedShare: 0, ourCost: 9000, extraRows: [["Východní plot 75 %", "6 750 Kč"], ["Tapety 25 %", "2 250 Kč"], ["Materiál - podhrabové desky a příslušenství", "1 859 Kč"]] },
          projects: ["🧱 Východní plot", "🧱 Ploty a zeď", "🏠 Tapety"],
          notes: "Pracovala plná parta: Ivan, Vasil a Tatíno celý pracovní den. Náklad práce: 3 osoby x 3 000 Kč = 9 000 Kč. Práce se dělí mezi naše projekty: 75 % východní plot = 6 750 Kč a 25 % tapety = 2 250 Kč. Východní plot byl kompletně dokončen. Materiál podhrabové desky a příslušenství je dle účtenky Ploty Dobrý & Urbánek uhrazený a dodaný za 1 859 Kč. Práce i materiál jsou 100 % náš náklad mimo vyúčtování s Loffelmanovými.",
        },
      },
      { id: "2026-07-05", day: 5, label: "5.7.", type: "off", title: "Nepracovalo se" },
      { id: "2026-07-06", day: 6, label: "6.7.", type: "off", title: "Nepracovalo se" },
      {
        id: "2026-07-07",
        day: 7,
        label: "7.7.",
        type: "shared",
        title: "Armovací stěrka",
        short: "Stěrka",
        tooltip: "7.7. Armovací stěrka a příprava na finální omítku / Tatíno, Vasil / 6 000 Kč",
        detail: {
          date: "7. 7. 2026",
          workers: ["Tatíno", "Vasil"],
          done: ["Armovací stěrka na driveway zídce", "Armovací stěrka na podezdívce pod WPC", "Příprava obou zídek na finální silikonovou omítku"],
          finance: { total: 6000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 6000, ourSharedShare: 3000, neighborSharedShare: 3000, ourCost: 3000 },
          projects: ["🚗 Driveway zídka", "🪵 Zahradní přepažení"],
          notes: "Ivan tento den nepracoval. Celý den pracovali Tatíno a Vasil, sazba dne je 2 osoby x 3 000 Kč = 6 000 Kč. Nejedná se o finální omítku. Proběhla armovací vrstva jako podklad pod finální silikonovou omítku Mistral silikon 1,5H TB. Práce je sdílený náklad s Loffelmanovými a dělí se 50 / 50.",
        },
      },
      {
        id: "2026-07-08",
        day: 8,
        label: "8.7.",
        type: "mixed",
        title: "Tapety + zídka + sousedé",
        short: "Tapety/Zídka",
        tooltip: "8.7. Tapety, společná zídka a dlažba u Loffelmanových / Tatíno, Vasil / 5 h",
        detail: {
          date: "8. 7. 2026",
          workers: ["Tatíno", "Vasil"],
          done: ["Tapety - dokončení ložnice", "Společná zídka - navazující práce", "Dlažba u Loffelmanových - finalizace cca 2 m²"],
          finance: {
            total: 2250,
            ownPercent: 50,
            sharedPercent: 50,
            ownAmount: 1125,
            sharedAmount: 1125,
            ourSharedShare: 562.5,
            neighborSharedShare: 562.5,
            ourCost: 1687.5,
            extraRows: [["🏡 Projekt Loffelmanových", "Pokládka dlažby cca 2 m² / 2 h / 1 500 Kč / uhrazeno Trantinovými / 100 % náklad Loffelmanových"], ["🪨 Materiál dlažby Loffelmanových", "cca 2 m² x 700 Kč = 1 400 Kč / 100 % náklad Loffelmanových"], ["Pohledávka za Loffelmanovými", "2 900 Kč"], ["Tapety 100 % náš projekt", "1,5 h / 1 125 Kč"], ["Společná zídka 50 / 50", "1,5 h / 1 125 Kč"]],
          },
          projects: ["🏠 Tapety", "🪵 Zahradní přepažení", "🏡 Projekt Loffelmanových"],
          notes: "Tatíno a Vasil pracovali 5 hodin. Rozdělení dne: 2 h pokládka dlažby u Loffelmanových na ploše cca 2 m² jako 100 % jejich projekt, 1,5 h společná zídka 50 / 50 a 1,5 h Tapety jako 100 % náš projekt. Dlažba u Löffelmanových byla uhrazena Trantinovými, nezvyšuje náš projekt ani sdílený projekt a zakládá pohledávku Trantinových vůči Löffelmanovým: práce 1 500 Kč + materiál 1 400 Kč = 2 900 Kč.",
        },
      },
      { id: "2026-07-09", day: 9, label: "9.7.", type: "off", title: "Nepracovalo se" },
      { id: "2026-07-10", day: 10, label: "10.7.", type: "off", title: "Nepracovalo se" },
      {
        id: "2026-07-11",
        day: 11,
        label: "11.7.",
        type: "shared",
        title: "Stříšky a penetrace",
        short: "Zídky",
        tooltip: "11.7. Stříšky a penetrace zídek / Tatíno, Vasil / 6 000 Kč",
        detail: {
          date: "11. 7. 2026",
          workers: ["Tatíno", "Vasil"],
          done: ["Driveway zídka - lepení stříšek", "Driveway zídka - penetrace před finální omítkou", "Západní zídka pod WPC - lepení stříšek", "Západní zídka pod WPC - penetrace", "Západní zídka pod WPC - řezání stříšek podle potřebných rozměrů"],
          finance: { total: 6000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 6000, ourSharedShare: 3000, neighborSharedShare: 3000, ourCost: 3000 },
          projects: ["🚗 Driveway zídka", "🪵 Zahradní přepažení"],
          notes: "Ivan tento den nepracoval. Pracovali Tatíno a Vasil, standardní den dvoučlenné party za 6 000 Kč. Celý pracovní den spadal do společného projektu s Loffelmanovými a dělí se 50 / 50.",
        },
      },
      {
        id: "2026-07-14",
        day: 14,
        label: "14.7.",
        type: "off",
        title: "Nepracovalo se",
        tooltip: "14.7. Nepracovalo se / bez nákladu práce",
      },
      {
        id: "2026-07-15",
        day: 15,
        label: "15.7.",
        type: "shared",
        title: "Omítky a plotová pole",
        short: "Omítky/Pole",
        tooltip: "15.7. Dokončovací vrstvy a montáž plotových polí / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "15. 7. 2026",
          workers: ["Ivan", "Vasil", "Tatíno"],
          done: ["Omítka / dokončovací vrstvy na driveway zídce", "Omítka / dokončovací vrstvy na WPC západním plotu", "Montáž plotového pole / plotových polí"],
          finance: { total: 9000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 9000, ourSharedShare: 4500, neighborSharedShare: 4500, ourCost: 4500 },
          projects: ["🚗 Driveway zídka", "🪵 Zahradní přepažení"],
          notes: "Pracovala plná parta: Ivan, Vasil a Tatíno. Denní sazba: 3 osoby x 3 000 Kč = 9 000 Kč. Podle aktuální projektové evidence jde o společnou práci související s driveway zídkou a WPC západním plotem, dělení 50 / 50 s Loffelmanovými.",
        },
      },
    ],
  },
  settlement: {
    intro:
      "Průběžné vyúčtování položek, které se budou dělit rovným dílem mezi nás a Lofflemanovy. Jméno Loffleman označuje sousedy; projektová položka se jmenuje Zahradní přepažení.",
    cards: [
      ["Materiál 50 / 50", "split", "🪵 WPC desky + sloupky + příslušenství", "37 669 Kč", "Náš podíl: 18 834,50 Kč\nPodíl Lofflemanových: 18 834,50 Kč"],
      ["Materiál 50 / 50", "split", "🚗 Hliníkové plotové pole driveway", "14 721 Kč", "Náš podíl: 7 360,50 Kč\nPodíl Lofflemanových: 7 360,50 Kč"],
      ["Materiál 50 / 50", "split", "🧱 Ztracené bednění a beton", "12 282 Kč", "Projekt: Driveway zídka\nNáš podíl: 6 141 Kč\nPodíl Lofflemanových: 6 141 Kč"],
      ["Materiál 50 / 50", "split", "🧱 OBI materiál k přepažení", "12 964 Kč", "Náš podíl: 6 482 Kč\nPodíl Lofflemanových: 6 482 Kč"],
      ["Materiál 50 / 50", "split", "🎨 Omítka, stříšky a lišty", "7 639 Kč", "Náš podíl: 3 819,50 Kč\nPodíl Lofflemanových: 3 819,50 Kč"],
      ["Materiál 50 / 50", "split", "🧾 T+L doplňková účtenka", "432 Kč", "Náš podíl: 216 Kč\nPodíl Lofflemanových: 216 Kč"],
      ["Práce 50 / 50", "split", "👷 Sdílená práce 23. 6.-15. 7.", "67 575 Kč", "Náš podíl: 33 787,50 Kč\nPodíl Lofflemanových: 33 787,50 Kč"],
      ["Známý základ", "good", "💰 Aktuálně známé sdílené náklady", "153 282 Kč", "Náš podíl: 76 641 Kč\nPodíl Lofflemanových: 76 641 Kč"],
      ["Pohledávka", "wait", "🏡 Pohledávka za Loffelmanovými", "2 900 Kč", "Dlažba u Loffelmanových cca 2 m²: práce 1 500 Kč + materiál 1 400 Kč. Uhrazeno Trantinovými, 100 % náklad Loffelmanových, mimo 50 / 50 základ."],
    ],
    headers: ["Položka", "Celkem", "Dělení", "Náš podíl", "Podíl Lofflemanových", "Stav"],
    rows: [
      ["🪵 WPC desky + sloupky + příslušenství", "37 669 Kč", "50 / 50", "18 834,50 Kč", "18 834,50 Kč", "✅ zaplaceno / objednáno"],
      ["🚗 Hliníkové plotové pole driveway", "14 721 Kč", "50 / 50", "7 360,50 Kč", "7 360,50 Kč", "✅ zaplaceno námi"],
      ["🧱 Ztracené bednění a beton - Driveway zídka", "12 282 Kč", "50 / 50", "6 141 Kč", "6 141 Kč", "✅ zaplaceno námi, T+L účtenky, redukce na vozík vyřazeny"],
      ["🧱 OBI materiál k přepažení - účtenky ve várkách", "12 964 Kč", "50 / 50", "6 482 Kč", "6 482 Kč", "✅ zaplaceno námi"],
      ["🎨 Materiál omítka a lišty - driveway + WPC", "7 639 Kč", "50 / 50", "3 819,50 Kč", "3 819,50 Kč", "✅ zaplaceno námi, IMG_8601.JPG"],
      ["🧾 T+L doplňková účtenka", "432 Kč", "50 / 50", "216 Kč", "216 Kč", "✅ zaevidováno, IMG_8603.JPG"],
      ["👷 Práce 23. 6. - sdílená část 50 % dne", "4 500 Kč", "50 / 50", "2 250 Kč", "2 250 Kč", "✅ zaevidováno"],
      ["👷 Práce 24. 6. - sdílená část 75 % dne", "6 750 Kč", "50 / 50", "3 375 Kč", "3 375 Kč", "✅ zaevidováno"],
      ["👷 Práce 25. 6. - sdílená část 75 % dne", "6 750 Kč", "50 / 50", "3 375 Kč", "3 375 Kč", "✅ zaevidováno"],
      ["👷 Práce 26. 6. - sdílená část 50 % dne", "4 500 Kč", "50 / 50", "2 250 Kč", "2 250 Kč", "✅ zaevidováno"],
      ["👷 Práce 29. 6. - sdílená část 20 % dne", "1 200 Kč", "50 / 50", "600 Kč", "600 Kč", "✅ zaevidováno"],
      ["👷 Práce 30. 6. - výkop driveway zídky", "6 000 Kč", "50 / 50", "3 000 Kč", "3 000 Kč", "✅ zaevidováno"],
      ["👷 Práce 1. 7. - driveway zídka 75 % dne", "6 750 Kč", "50 / 50", "3 375 Kč", "3 375 Kč", "✅ zaevidováno"],
      ["👷 Práce 2. 7. - driveway zídka", "9 000 Kč", "50 / 50", "4 500 Kč", "4 500 Kč", "✅ zaevidováno"],
      ["👷 Práce 7. 7. - armovací stěrka a příprava na omítku", "6 000 Kč", "50 / 50", "3 000 Kč", "3 000 Kč", "✅ zaevidováno"],
      ["👷 Práce 8. 7. - společná zídka 1,5 h", "1 125 Kč", "50 / 50", "562,50 Kč", "562,50 Kč", "✅ zaevidováno"],
      ["🏡 Projekt Loffelmanových - dlažba cca 2 m²", "1 500 Kč", "100 % Loffelmanovi", "0 Kč", "1 500 Kč", "✅ pohledávka Trantinových"],
      ["🪨 Materiál dlažby Loffelmanových cca 2 m²", "1 400 Kč", "100 % Loffelmanovi", "0 Kč", "1 400 Kč", "✅ hrazeno Trantinovými"],
      ["👷 Práce 11. 7. - stříšky a penetrace zídek", "6 000 Kč", "50 / 50", "3 000 Kč", "3 000 Kč", "✅ zaevidováno"],
      ["👷 Práce 15. 7. - omítky a plotová pole", "9 000 Kč", "50 / 50", "4 500 Kč", "4 500 Kč", "✅ zaevidováno"],
      ["🔩 Spojovací materiál", "⏳ doplnit", "50 / 50", "⏳ doplnit", "⏳ doplnit", "průběžně"],
      ["🪨 Dlažba u společné zídky", "⏳ spočítat", "50 / 50", "⏳ spočítat", "⏳ spočítat", "čeká zaměření"],
      ["👷 Pokládka dlažby", "⏳ spočítat", "50 / 50", "⏳ spočítat", "⏳ spočítat", "čeká"],
    ],
    total: ["Známý společný základ", "153 282 Kč", "", "76 641 Kč", "76 641 Kč", "bez položek TBD"],
    breakdown: [
      ["Materiál", "split", "📦 Materiál známý", "85 707 Kč", "Náš podíl: 42 853,50 Kč\nPodíl Lofflemanových: 42 853,50 Kč"],
      ["Práce", "split", "👷 Práce známá", "67 575 Kč", "Náš podíl: 33 787,50 Kč\nPodíl Lofflemanových: 33 787,50 Kč"],
      ["Pohledávka", "wait", "🏡 Náklady uhrazené Trantinovými za Loffelmanovy", "2 900 Kč", "Dlažba u Loffelmanových: práce 1 500 Kč + materiál 1 400 Kč. Nezvyšuje náš projekt ani sdílený projekt."],
      ["Doplnit", "wait", "⏳ Otevřené položky", "", "Spojovací materiál, dlažba a pokládka dlažby."],
    ],
  },
  settlementReceivable: {
    note:
      "K úhradě od Loffelmanových zahrnuje pouze jejich podíl na nákladech hrazených Trantinovými a 100 % náklady Loffelmanových hrazené Trantinovými. Nejde o celý společný základ.",
    cards: [
      ["50 / 50", "split", "🤝 Sdílené 50 / 50", "76 641 Kč", "Podíl Loffelmanových ze známého společného základu 153 282 Kč."],
      ["100 % L", "wait", "🏡 100 % Loffelmanovi, hrazeno námi", "2 900 Kč", "Dlažba u Loffelmanových: práce 1 500 Kč + materiál 1 400 Kč."],
      ["Uhrazeno", "good", "✅ Už uhrazeno Loffelmanovými", "0 Kč", "Zatím neevidujeme příchozí platbu od Loffelmanových."],
      ["K úhradě", "wait", "💸 Zbývá zaplatit nám", "79 541 Kč", "76 641 Kč ze sdílených nákladů + 2 900 Kč čistě jejich náklad."],
    ],
    formula: [
      ["Podíl Loffelmanových na sdíleném materiálu", "42 853,50 Kč"],
      ["Podíl Loffelmanových na sdílené práci", "33 787,50 Kč"],
      ["100 % náklady Loffelmanových hrazené námi", "2 900 Kč"],
      ["Platby přijaté od Loffelmanových", "0 Kč"],
    ],
    headers: ["Kategorie", "Položka", "Celkem", "K úhradě od Loffelmanových", "Stav"],
    rows: [
      ["Sdílený materiál 50 / 50", "WPC materiál", "37 669 Kč", "18 834,50 Kč", "✅ zaplaceno námi"],
      ["Sdílený materiál 50 / 50", "Driveway plotové pole", "14 721 Kč", "7 360,50 Kč", "✅ zaplaceno námi"],
      ["Sdílený materiál 50 / 50", "Ztracené bednění a beton", "12 282 Kč", "6 141 Kč", "✅ zaplaceno námi"],
      ["Sdílený materiál 50 / 50", "OBI materiál k přepažení", "12 964 Kč", "6 482 Kč", "✅ zaplaceno námi"],
      ["Sdílený materiál 50 / 50", "Omítka, stříšky a lišty", "7 639 Kč", "3 819,50 Kč", "✅ zaplaceno námi"],
      ["Sdílený materiál 50 / 50", "T+L doplňková účtenka", "432 Kč", "216 Kč", "✅ evidováno, hradil Ivan / k proplacení"],
      ["Sdílená práce 50 / 50", "Sdílená práce do 15. 7.", "67 575 Kč", "33 787,50 Kč", "✅ evidováno námi"],
      ["100 % Loffelmanovi", "Pokládka dlažby Loffelmanových cca 2 m²", "1 500 Kč", "1 500 Kč", "✅ zaplaceno Trantinovými"],
      ["100 % Loffelmanovi", "Materiál dlažby Loffelmanových cca 2 m²", "1 400 Kč", "1 400 Kč", "✅ hrazeno Trantinovými"],
      ["Platby", "Uhrazeno Loffelmanovými", "0 Kč", "-0 Kč", "⏳ čeká na úhradu"],
    ],
    total: ["K úhradě od Loffelmanových", "", "156 182 Kč", "79 541 Kč", "bez přijatých plateb"],
  },
  projects: [
    ["🧱 Ploty a zeď", ["✅ Vybráno", "✅ Objednáno", "✅ Zaplaceno", "✅ Dovezeno", "✅ Jižní plot dokončen bez podhrabovek", "✅ Východní plot - stržení původního plotu", "✅ Východní plot - řezání původní podezdívky", "✅ Východní plot - vrty pro sloupky", "✅ Východní plot - betonování sloupků", "✅ Východní plot - montáž plotových panelů", "✅ Východní plot - montáž podhrabových desek", "✅ Podhrabové desky a příslušenství dle účtenky 1 859 Kč", "✅ Kompletní dokončení východního plotu 4. 7. 2026"], "Hotovo", "good"],
    ["🚗 Driveway zídka", ["✅ Výkop základů 30. 6.", "✅ Práce 1. 7. - 75 % dne jako společný projekt", "✅ Pokračování realizace 2. 7. celou partou", "✅ Armovací stěrka", "✅ Příprava na finální omítnutí", "✅ Nalepeny stříšky", "✅ Penetrace pod finální silikonovou omítku", "✅ Omítka / dokončovací práce probíhaly do 15. 7.", "✅ Materiál Mistral a navazující materiál zaevidován jako sdílený", "⏳ Doplnit finální stav omítky", "🤝 Dělení společné práce a materiálu 50 / 50 s Lofflemanovými"], "Společný projekt", "split"],
    ["🪵 Zahradní přepažení", ["✅ ROJA WPC desky a sloupky dorazily", "✅ WPC desky nahozeny", "✅ Podezdívka / ztracené bednění proběhlo", "✅ Armovací stěrka podezdívky pod WPC", "✅ Příprava na finální omítnutí", "✅ Nalepeny stříšky", "✅ Penetrace", "✅ Řezání stříšek", "✅ Omítka / dokončovací práce probíhaly do 15. 7.", "✅ Materiál zaevidován jako sdílený", "✅ OBI účtenky za beton a bednění zaevidovány", "⏳ Doplnit finální stav omítky"], "Zbývá finální stav omítky", "wait"],
    ["🪵 Pergola", ["✅ Rozpočet pergoly schválen: 207 000 Kč", "✅ Patky hotové", "⏳ Čeká termín realizace", "⏳ Navazující práce budou doplněny podle realizace"], "Čeká termín", "wait"],
    ["🌳 Zahradní domek", ["⏳ Projekt plánován", "🪨 Dlažba pod zahradní domek (cca 26 m²)", "⏳ Odhad nákladu: 18 200 Kč", "⏳ Realizace bude navázaná na finální umístění domku"], "Plánováno", "wait"],
    ["⚡ Elektro", "Kornhauser bez kolize, 380 V v rozvaděči, řešit s tátou zachování 11 kW nabíjení."],
    ["🏊 Bazén", "Čeká budget a finální plán."],
    ["🧱 Zábradlí", ["✅ Realizace dokončena", "✅ Namontováno", "✅ Uhrazeno", "✅ Projekt uzavřen", "🔒 100 % soukromý náklad, mimo sdílené vyúčtování"], "Dokončeno", "good"],
    ["🪞 Zrcadla", ["✅ Cena doplněna: 10 348 Kč", "✅ Výška umístění schválena", "✅ Montáž dokončena", "✅ Projekt dokončen 1. 7. 2026"], "Dokončeno", "good"],
    ["🧱 Tapety", ["✅ Tapeta - materiál pořízen / uhrazeno: 6 000 Kč", "✅ Práce 1. 7. - 25 % dne", "✅ Tapeta v dětském pokoji hotová", "✅ Tapeta v ložnici hotová", "✅ Projekt Tapety dokončen 8. 7. 2026"], "Hotovo", "good"],
    ["🏡 Projekt Löffelmanových", ["✅ Pokládka dlažby", "✅ Plocha cca 2 m²", "✅ Práce 2 hodiny", "✅ Hodnota práce 1 500 Kč", "✅ Materiál dlažby 1 400 Kč", "✅ Uhrazeno Trantinovými", "📌 Pohledávka za Loffelmanovými: 2 900 Kč", "🔒 Mimo náš projekt i mimo sdílený projekt 50 / 50"], "Pohledávka", "wait"],
    ["💡 Osvětlení", ["⏳ Světlo - šatna Lucie", "Poznámka: čeká na předání / dovoz od Tondy.", "⏳ Světlo nad kuchyňský ostrůvek", "⏳ Světlo - chodba 2NP", "⏳ Dodělat LED track - chodba 1NP"], "Probíhá", "wait"],
  ],
  plan: [
    {
      title: "🧱 Ploty",
      items: [
        ["ploty-vybrany", "Ploty vybrány", true],
        ["ploty-objednany", "Ploty objednány", true],
        ["ploty-zaplaceny", "Ploty zaplaceny", true],
        ["ploty-dovezeny", "Ploty a podhrabovky dovezeny", true],
        ["jizni-plot-hotov", "Jižní plot dokončen bez podhrabovek", true],
        ["vychodni-plot-strzeni", "Stržení původního plotu", true],
        ["vychodni-plot-rezani-podezdivky", "Řezání původní podezdívky", true],
        ["vychodni-plot-vrty", "Vrty pro sloupky", true],
        ["vychodni-plot-betonaz-sloupku", "Betonování sloupků", true],
        ["vychodni-plot-montaz-panelu", "Montáž plotových panelů", true],
        ["vychodni-plot-podhrabove-desky", "Montáž podhrabových desek", true],
        ["vychodni-plot-podhrabovky-uctenka", "Podhrabové desky a příslušenství dle účtenky 1 859 Kč", true],
        ["vychodni-plot-finalni-dokonceni", "Kompletní dokončení východního plotu 4. 7. 2026", true],
      ],
    },
    {
      title: "🪵 Zahradní přepažení",
      items: [
        ["roja-dorazila", "ROJA WPC materiál dorazil", true],
        ["wpc-nahozeny", "WPC desky nahozeny", true],
        ["ztracene-bedneni", "Ztracené bednění / podezdívka proběhla", true],
        ["armovaci-sterka-wpc-7-7", "Armovací stěrka podezdívky pod WPC", true],
        ["priprava-omitka-wpc-7-7", "Příprava na finální omítnutí", true],
        ["strisky-wpc-11-7", "Nalepeny stříšky", true],
        ["penetrace-wpc-11-7", "Penetrace", true],
        ["rezani-strisek-wpc-11-7", "Řezání stříšek", true],
        ["omitka-prubeh-15-7", "Omítka / dokončovací práce probíhaly do 15. 7.", true],
        ["omitka-material-tl-15-7", "Mistral a navazující materiál zaevidován jako sdílený", true],
        ["omitka-mistral", "Doplnit finální stav omítky Mistral 1,5H TB", false],
      ],
    },
    {
      title: "🤝 Vyúčtování",
      items: [
        ["podpis-sousedky-plot", "Podpis sousedky k výměně plotu a podhrabovkám máme", true],
        ["prace-23-sdilena", "Práce 23. 6. sdílená 50 % dne", true],
        ["prace-24-sdilena", "Práce 24. 6. sdílená 75 % dne", true],
        ["prace-25-sdilena", "Práce 25. 6. sdílená 75 % dne", true],
        ["prace-26-sdilena", "Práce 26. 6. sdílená 50 % dne", true],
        ["prace-29-sdilena", "Práce 29. 6. sdílená 20 % dne", true],
        ["prace-30-6-sdilena", "Práce 30. 6. driveway zídka sdílená 100 % dne", true],
        ["prace-1-7-sdilena", "Práce 1. 7. driveway zídka sdílená 75 % dne", true],
        ["prace-2-7-sdilena", "Práce 2. 7. driveway zídka sdílená 100 % dne", true],
        ["prace-7-7-sdilena", "Práce 7. 7. armovací stěrka a příprava na omítku sdílená 100 % dne", true],
        ["prace-8-7-sdilena", "Práce 8. 7. společná zídka 1,5 h sdílená 50 / 50", true],
        ["prace-11-7-sdilena", "Práce 11. 7. stříšky a penetrace zídek sdílená 100 % dne", true],
        ["prace-15-7-sdilena", "Práce 15. 7. omítky a plotová pole sdílená 100 % dne", true],
        ["obi-uctenky-sdilene", "OBI účtenky za beton, bednění, roxor a klíny zaevidovány", true],
        ["material-omitka-listy-15-7", "T+L účtenky za omítku, stříšky a lišty za 7 639 Kč zaevidovány 50 / 50", true],
        ["obi-nesdilene-mimo-sdileni", "OBI nesdílené účtenky za 3 860 Kč vyjmuty ze sdíleného vyúčtování", true],
        ["dlazba-sousede-8-7", "Dlažba u Loffelmanových cca 2 m² / 2 h zaevidována mimo náš i sdílený rozpočet", true],
      ],
    },
    {
      title: "🧱 Zábradlí",
      items: [
        ["zabradli-realizace", "Realizace dokončena", true],
        ["zabradli-montaz", "Zábradlí namontováno", true],
        ["zabradli-uhrazeno", "Faktura uhrazena / zařazena mezi potvrzené náklady", true],
        ["zabradli-uzavreno", "Projekt uzavřen jako 100 % náš náklad", true],
      ],
    },
    {
      title: "🌳 Zahradní domek",
      items: [
        ["domek-dlazba-plan", "Dlažba pod zahradní domek (cca 26 m²) naplánována", false],
        ["domek-dlazba-termin", "Doplnit termín realizace dlažby pod zahradní domek", false],
      ],
    },
    {
      title: "🪞 Zrcadla",
      items: [
        ["zrcadla-cena", "Doplnit cenu", true],
        ["zrcadla-vyska-lucie", "Schválit výšku umístění s Lucií", true],
        ["zrcadla-montaz", "Montáž", true],
      ],
    },
    {
      title: "🧱 Tapety",
      items: [
        ["tapety-material", "Tapeta - materiál pořízen / uhrazeno: 6 000 Kč", true],
        ["tapety-prace-1-7", "Práce na tapetách 1. 7. - 25 % dne", true],
        ["tapety-detsky-pokoj", "Tapeta v dětském pokoji hotová", true],
        ["tapety-loznice", "Tapeta v ložnici hotová", true],
        ["tapety-dokonceno-8-7", "Projekt Tapety dokončen 8. 7. 2026", true],
      ],
    },
    {
      title: "💡 Osvětlení",
      items: [
        ["osvetleni-satna-tonda", "Převzít světlo do šatny od Tondy", false],
        ["osvetleni-ostruvek", "Namontovat světlo nad ostrůvek", false],
        ["osvetleni-chodba-2np", "Namontovat světlo v chodbě 2NP", false],
        ["osvetleni-led-track-1np", "Dokončit LED track v chodbě 1NP", false],
      ],
    },
  ],
  electricity: [
    ["✅ Uzavřeno", "good", "Hlavní kabel", "Kornhauser kontaktován. Kabel vede u souseda a není v kolizi."],
    ["✅ 380 V", "good", "Rozvaděč", "V hlavním rozvaděči je 380 V."],
    ["⚠️ Riziko", "risk", "Nabíjení 11 kW", "Rozvázáním 380 V pro zahradu můžeme přijít o 11 kW nabíjení."],
    ["⏳ Úkol", "wait", "Dotáhnout tátu", "Najít řešení bez ztráty 11 kW nabíjení."],
  ],
  timeline: [
    {
      date: "17. 6. 2026",
      status: "done",
      icon: "🚀",
      title: "Start stavby",
      body: "Ivanova parta zahájila práce.",
    },
    {
      date: "23. 6. 2026",
      status: "done",
      icon: "🤝",
      title: "Společný projekt",
      body: "Začala práce na zahradním přepažení s Löffelmanovými.",
    },
    {
      date: "26. 6. 2026",
      status: "done",
      icon: "🧱",
      title: "Jižní plot",
      body: "Jižní plot dokončen bez podhrabovek.",
    },
    {
      date: "26. 6. 2026",
      status: "done",
      icon: "🪜",
      title: "Zábradlí",
      body: "Zábradlí finalizováno.",
    },
    {
      date: "30. 6. 2026",
      status: "done",
      icon: "🚗",
      title: "Driveway zídka",
      body: "Zahájen výkop základů pro driveway zídku.",
    },
    {
      date: "3. 7. 2026",
      status: "done",
      icon: "🧱",
      title: "Východní plot",
      body: "Proběhly vrty, betonování a montáž plotových panelů.",
    },
    {
      date: "4. 7. 2026",
      status: "done",
      icon: "🧱",
      title: "Východní plot dokončen",
      body: "Po dokončení montáže panelů a podhrabových desek byl východní plot kompletně dokončen.",
    },
    {
      date: "4. 7. 2026",
      status: "done",
      icon: "🏠",
      title: "Tapety",
      body: "Dětský pokoj hotový, ložnice čekala na dokončení.",
    },
    {
      date: "7. 7. 2026",
      status: "done",
      icon: "🧱",
      title: "Příprava na finální omítku",
      body: "Dokončena armovací stěrka na driveway zídce i podezdívce pod WPC jako sdílená práce s Löffelmanovými.",
    },
    {
      date: "8. 7. 2026",
      status: "done",
      icon: "🏠",
      title: "Tapety dokončeny",
      body: "Po dokončení ložnice je projekt Tapety hotový. Část dne proběhla výhradně pro Löffelmanovy mimo naše a sdílené náklady.",
    },
    {
      date: "11. 7. 2026",
      status: "done",
      icon: "🧱",
      title: "Zídky připraveny na finální omítku",
      body: "Na driveway zídce i západní zídce pod WPC byly nalepeny stříšky a provedena penetrace. Obě konstrukce jsou připravené pro finální silikonovou omítku.",
    },
    {
      date: "15. 7. 2026",
      status: "done",
      icon: "🎨",
      title: "Omítky a plotová pole",
      body: "Do deníku doplněny omítkové / dokončovací práce na driveway zídce a WPC západním plotu včetně montáže plotových polí. Pracovní sazby zůstávají k doplnění.",
    },
    {
      date: "Budoucí",
      status: "planned",
      icon: "🪵",
      title: "Pergola",
      body: "Čeká termín realizace.",
    },
    {
      date: "Budoucí",
      status: "planned",
      icon: "🏠",
      title: "Zahradní domek",
      body: "Plánovaná navazující etapa.",
    },
  ],
  missing: [
    "Termín realizace pergoly.",
    "Táta: návrh elektro řešení bez ztráty 11 kW nabíjení.",
    "Doplnit termín realizace dlažby pod zahradní domek cca 26 m².",
    "Doplnit finální stav omítky a případné pracovní sazby k driveway zídce a zahradnímu přepažení.",
    "Osvětlení: převzít světlo do šatny od Tondy, namontovat světlo nad ostrůvek, světlo v chodbě 2NP a dokončit LED track v chodbě 1NP.",
  ],
};
