window.ZAHRADA_DASHBOARD = {
  title: "Zahradní projekt - master dashboard",
  intro:
    "Konsolidovaná verze s kompletním výpočtem práce, deníkem 23. 6.-6. 8., vyúčtováním se sousedy a aktuálními novinkami.",
  nav: [
    ["overview", "🏡 Přehled"],
    ["recent", "🆕 Změny"],
    ["projects", "✅ Projekty"],
    ["worklog", "📒 Deník"],
    ["finance", "💰 Finance"],
    ["plan", "📋 Plán"],
    ["docs", "🔗 Dokumenty"],
    ["electricity", "⚡ Elektřina"],
    ["timeline", "📅 Timeline"],
    ["missing", "⚠️ Doplnit"],
  ],
  finance: {
    overview: [
      {
        tone: "good",
        title: "💰 Celková investice",
        body: "Kolik celý projekt stojí / bude stát?",
        metrics: [
          ["Potvrzené / objednané", "667 319,50 Kč"],
          ["Včetně práce a odhadů", "685 519,50 Kč"],
          ["Plánované / odhadované", "18 200 Kč"],
          ["Rozdíl od potvrzeného", "18 200 Kč"],
        ],
      },
      {
        tone: "wait",
        title: "💸 Cashflow",
        body: "Kolik peněz už odešlo a co ještě čeká na platbu?",
        metrics: [
          ["Zaplaceno", "398 137,50 Kč"],
          ["Čeká na úhradu", "61 750 Kč"],
          ["Proplaceno Ivanovi", "134 000 Kč"],
          ["Otevřené závazky", "61 750 Kč"],
        ],
      },
      {
        tone: "split",
        title: "🤝 Löffelmanovi — projekt uzavřen",
        body: "Dokončeno 17. 7. 2026. Kompaktní souhrn uzavřeného vyúčtování.",
        metrics: [
          ["Stav", "✅ Dokončeno 17. 7. 2026"],
          ["Známý společný základ", "162 282 Kč"],
          ["Náš podíl", "81 141 Kč"],
          ["Podíl Löffelmanových", "81 141 Kč"],
          ["100 % jejich náklad hrazený námi", "2 900 Kč"],
          ["Celkem k úhradě Trantinovým", "84 041 Kč"],
          ["Dosud uhrazeno Löffelmanovými", "0 Kč"],
          ["Zbývá uhradit", "84 041 Kč"],
        ],
      },
      {
        tone: "good",
        title: "👷 Ivanova parta",
        body: "Kolik už Ivanova parta odpracovala a kolik jim ještě dlužíme?",
        metrics: [
          ["Celková práce", "195 750 Kč"],
          ["Vyplaceno Ivanovi celkem", "134 000 Kč"],
          ["Účtenky Ivanovi", "✅ vyrovnáno"],
          ["Zbývá doplatit za práci", "61 750 Kč"],
          ["Dny", "18 plných + 5 dvoučlenných + 1 částečný"],
        ],
      },
    ],
    cashflow: {
      headers: ["Metrika", "Částka", "Poznámka"],
      rows: [
        ["Zaplaceno", "398 137,50 Kč", "Uhrazené platby evidované v platbách včetně vyrovnání Ivanovi, podhrabových desek, tapety, dlažby BAUHAUS k vířivce, štěrku 0/32 a sdílených účtenek T+L."],
        ["Čeká na úhradu", "61 750 Kč", "Zbývající doplatek za práci Ivanovy party po zaevidování práce 6. 8. 2026."],
        ["Proplaceno Ivanovi", "134 000 Kč", "72 000 Kč dne 30. 6. a 62 000 Kč dne 15. 7. 2026."],
        ["Práce Ivanovy party", "195 750 Kč", "Čistá evidence výkonu: pouze odpracované dny a sazby, bez materiálu a účtenek."],
        ["Účtenky Ivanovi", "✅ vyrovnáno", "Batch účtenek hrazených Ivanem už neevidujeme jako otevřený závazek."],
        ["Platba Ivanovi 15. 7.", "62 000 Kč", "✅ uhrazeno jako skutečná cashflow platba; nezvyšuje práci, materiál ani sdílené náklady."],
        ["Otevřené závazky", "61 750 Kč", "Zbývající doplatek za práci: 195 750 Kč minus 134 000 Kč vyplaceno Ivanovi."],
      ],
      total: ["Celkem otevřeno", "61 750 Kč", "Zbývá doplatek za práci Ivanovy party"],
    },
  },
  workPaymentLedger: {
    note:
      "Platby Ivanovi jsou zatím evidované souhrnně. Neexistuje explicitní alokace, které konkrétní pracovní dny pokryla platba 72 000 Kč ani platba 62 000 Kč, proto jednotlivé dny zůstávají ve stavu nepřiřazeno.",
    defaultStatus: "unallocated",
    payments: [
      {
        id: "payment-2026-06-30",
        date: "30. 6. 2026",
        amount: 72000,
        recipient: "Ivan",
        type: "work-settlement",
      },
      {
        id: "payment-2026-07-15",
        date: "15. 7. 2026",
        amount: 62000,
        recipient: "Ivan",
        type: "work-settlement",
      },
    ],
    allocations: [],
  },
  overview: [
    {
      badge: "🔨 Probíhá",
      tone: "wait",
      title: "♨️ Vířivka + elektřina",
      body: "Aktivně běží příprava podkladu pro vířivku, štěrkové lože 0/32 a navazující zpevněné plochy.",
    },
    {
      badge: "✅ Uzavřeno",
      tone: "split",
      title: "🤝 Löffelmanovi",
      body: "Společný projekt je dokončený k 17. 7. 2026. K úhradě Trantinovým zůstává 84 041 Kč.",
    },
    {
      badge: "⚪ Nepřiřazeno",
      tone: "wait",
      title: "👷 Práce Ivanovy party",
      body: "Celková práce 195 750 Kč, vyplaceno 134 000 Kč, otevřený závazek 61 750 Kč. Platby zatím nejsou spárované s jednotlivými dny.",
    },
    {
      badge: "💰 Finance",
      tone: "good",
      title: "Celková investice",
      body: "Potvrzené / objednané náklady jsou 667 319,50 Kč. Včetně odhadů dashboard ukazuje 685 519,50 Kč.",
    },
  ],
  documents: [
    {
      title: "🎨 Vizualizace",
      label: "Otevřít",
      href: "https://drive.google.com/drive/folders/1T8yMMrG4i_ONeV4YYDIMt_nCTC70tfVn?usp=drive_link",
    },
    {
      title: "🎥 Videoprohlídka",
      label: "Otevřít",
      href: "https://drive.google.com/drive/folders/1hPTJq9R4rC93LgFnRT1XxNm9Bq4s2qg_?usp=drive_link",
    },
    {
      title: "📐 Plány zahrady",
      label: "Otevřít",
      href: "https://drive.google.com/drive/folders/11Yka0ctc8tWe06xxajmNqD6CEx1QtDaY",
    },
  ],
  budget: {
    cards: [
      ["✅ Schváleno", "good", "🪵 Pergola", "207 000 Kč"],
      ["✅ Zaplaceno + dovezeno", "good", "🧱 Ploty a podhrabovky", "31 305,98 Kč"],
      ["50 / 50", "split", "🪵 Zahradní přepažení WPC", "37 669 Kč"],
      ["50 / 50", "split", "🚗 Driveway plotové pole", "14 721 Kč"],
      ["50 / 50", "split", "🧱 Ztracené bednění a beton", "12 282 Kč", "Projekt: Driveway zídka. Zahrnuje sdílené OBI účtenky označené T+L z 1.-2. 7.; dvě redukce na vozík za 408 Kč byly vyřazeny z evidence. Hrazeno námi, podíl každé strany 6 141 Kč."],
      ["50 / 50", "split", "🧱 OBI sdílený materiál", "12 964 Kč", "Beton, ztracené bednění, roxor a klíny. Podíl každé strany 6 482 Kč."],
      ["50 / 50", "split", "🎨 Omítka, stříšky a lišty", "7 639 Kč", "T+L účtenky: Mistral omítka 4 356 Kč, OBI 1 039 Kč, OBI 1 404 Kč, stříšky a rohové lišty 840 Kč. Podíl každé strany 3 819,50 Kč."],
      ["50 / 50", "split", "🧾 T+L doplňková účtenka", "432 Kč", "Podíl každé strany 216 Kč. Účtenka je dostupná v detailu sdílených nákladů."],
      ["✅ Uhrazeno", "good", "🔌 OBI nesdílený materiál", "3 860 Kč", "Chránička, armovací tkanina, lepidlo, beton označený T a proplacený OBI materiál od Ivana. 100 % náš náklad."],
      ["✅ Uhrazeno + dodáno", "good", "🧱 Podhrabové desky", "1 859 Kč", "Dle účtenky Ploty Dobrý & Urbánek z 4. 7. 2026, IMG_8602.JPG. Projekt: Východní plot. 100 % náš náklad, mimo vyúčtování s Loffelmanovými."],
      ["✅ Položeno", "good", "🪨 Dlažba 14 m²", "9 800 Kč", "Zakoupeno, zaplaceno a položeno. Z toho cca 2 m² / 1 400 Kč patří Loffelmanovým a je vedeno jako 100 % jejich náklad hrazený námi."],
      ["✅ Uhrazeno", "good", "🧱 Ivan - cement", "5 644 Kč"],
      ["✅ Evidováno", "good", "👷 Práce Ivanovy party", "195 750 Kč", "Čistá evidence práce: odpracované dny a sazby bez materiálu a účtenek. Zahrnuje také 1 500 Kč práce 8. 7. pro Loffelmanovy, která není náš ani sdílený náklad, sdílený den 17. 7. za 9 000 Kč, vlastní dny 21., 25., 27. 7. a 6. 8. po 9 000 Kč a dvoučlenný den 3. 8. za 6 000 Kč."],
      ["✅ Uhrazeno", "good", "💸 Částečné vyrovnání Ivanovi", "72 000 Kč", "Vyplaceno 30. 6. 2026 proti evidované práci Ivanovy party."],
      ["✅ Uhrazeno", "good", "💸 Platba Ivanovi 15. 7.", "62 000 Kč", "Skutečná cashflow platba vůči Ivanovi. Nejde o nový projektový náklad."],
      ["✅ Vyrovnáno", "good", "💸 Účtenky Ivanovi", "vyrovnáno", "Batch účtenek hrazených Ivanem už neevidujeme jako otevřený závazek."],
      ["✅ Uhrazeno", "good", "🧱 Zábradlí", "80 109,12 Kč"],
      ["⏳ Odhad", "wait", "🪨 Dlažba pod zahradní domek", "18 200 Kč", "Plánovaná dlažba cca 26 m² pro budoucí zahradní domek."],
      ["✅ Dokončeno", "good", "🪞 Zrcadla", "10 348 Kč", "Zaplaceno a dokončeno 1. 7. 2026."],
      ["✅ Uhrazeno", "good", "🪑 Konzolový stolek", "4 847 Kč", "Samostatná evidovaná položka, zatím bez přiřazení k projektu."],
      ["✅ Uhrazeno", "good", "🧱 Tapeta", "6 000 Kč", "Materiál pro projekt Tapety. Účtenka není k dispozici. 100 % náš náklad mimo vyúčtování s Loffelmanovými."],
      ["✅ Uhrazeno", "good", "♨️ Dlažba k vířivce", "20 189,40 Kč", "BAUHAUS 27. 7. 2026, 2cm FOG L.GREY 59,3x. 100 % náš náklad mimo vyúčtování s Loffelmanovými. Účtenka IMG_8699.JPG je dostupná v detailní tabulce rozpočtu."],
      ["✅ Uhrazeno", "good", "🪨 Štěrk 0/32", "4 900 Kč", "Projekt Vířivka / zpevněné plochy. 100 % náš náklad. Cena bude později doplněna o případné další dodávky štěrku, pokud budou potřeba."],
    ],
    rows: [
      ["Pergola", "207 000 Kč", "✅ schváleno"],
      ["Ploty a podhrabovky", "31 305,98 Kč", "✅ zaplaceno a dovezeno"],
      ["Zahradní přepažení WPC", "37 669 Kč", "✅ objednáno, sdílené"],
      ["Driveway plotové pole", "14 721 Kč", "✅ uhrazeno námi, sdílené"],
      ["Ztracené bednění a beton - Driveway zídka", "12 282 Kč", "✅ uhrazeno námi, sdílené 50 / 50; T+L účtenky z 1.-2. 7., redukce na vozík vyřazeny"],
      ["OBI sdílený materiál k přepažení", "12 964 Kč", "✅ uhrazeno námi, sdílené 50 / 50"],
      ["Omítka, stříšky a lišty - Driveway + WPC", "7 639 Kč", { label: "✅ uhrazeno námi · Otevřít účtenku ↗", href: "assets/receipts/IMG_8601.JPG" }],
      ["T+L doplňková účtenka", "432 Kč", { label: "✅ sdílené 50 / 50 · Otevřít účtenku ↗", href: "assets/receipts/IMG_8603.JPG" }],
      ["OBI nesdílený materiál", "3 860 Kč", "✅ uhrazeno námi, mimo vyúčtování s Loffelmanovými; zahrnuje účtenku označenou T a proplacenou účtenku od Ivana"],
      ["Podhrabové desky", "1 859 Kč", "✅ uhrazeno a dodáno; Ploty Dobrý & Urbánek 4. 7. 2026; IMG_8602.JPG; projekt Východní plot; 100 % náš náklad mimo vyúčtování s Loffelmanovými"],
      ["Dlažba 14 m²", "9 800 Kč", "✅ zakoupeno, zaplaceno a položeno; cca 2 m² / 1 400 Kč jsou 100 % náklad Loffelmanových hrazený námi"],
      ["Ivan - cement a materiál", "5 644 Kč", "✅ uhrazeno 20. 6."],
      ["Práce Ivanovy party", "195 750 Kč", "✅ čistá evidence práce bez materiálu a účtenek; 8. 7. zahrnuje 1 500 Kč práce pro Loffelmanovy mimo náš i sdílený rozpočet; 17. 7. plná parta sdíleně 50 / 50; 21., 25., 27. 7. a 6. 8. plná parta 100 % náš projekt; 3. 8. dvoučlenná parta 100 % náš projekt"],
      ["Částečné vyrovnání Ivanovi", "72 000 Kč", "✅ uhrazeno 30. 6. 2026, platba proti závazku práce"],
      ["Platba Ivanovi 15. 7.", "62 000 Kč", "✅ uhrazeno jako cashflow; nezvyšuje práci, materiál ani sdílené náklady"],
      ["Účtenky Ivanovi", "vyrovnáno", "✅ batch účtenek hrazených Ivanem už není vedený jako otevřený závazek"],
      ["Zábradlí", "80 109,12 Kč", "✅ dokončeno, namontováno a uhrazeno - 100 % náš náklad"],
      ["Dlažba pod zahradní domek cca 26 m²", "18 200 Kč", "⏳ odhad"],
      ["Zrcadla", "10 348 Kč", "✅ zaplaceno a dokončeno 1. 7. 2026"],
      ["Konzolový stolek", "4 847 Kč", "✅ zaplaceno 1. 7. 2026, samostatná evidovaná položka"],
      ["Tapeta", "6 000 Kč", "✅ materiál pořízen / uhrazen; projekt Tapety; účtenka není k dispozici; 100 % náš náklad mimo vyúčtování s Loffelmanovými"],
      ["Dlažba k vířivce", "20 189,40 Kč", { label: "✅ uhrazeno námi · Otevřít účtenku ↗", href: "assets/receipts/IMG_8699.JPG" }],
      ["Štěrk 0/32", "4 900 Kč", "✅ uhrazeno; projekt Vířivka / zpevněné plochy; 100 % náš náklad; možné další dodávky budou doplněny později"],
    ],
    totals: [
      ["Nákladový součet včetně práce a odhadu", "685 519,50 Kč"],
      ["Potvrzené / objednané bez odhadu dlažby", "667 319,50 Kč"],
      ["Vyplaceno Ivanovi celkem", "134 000 Kč"],
      ["Zbývá doplatit Ivanovi celkem", "61 750 Kč"],
    ],
  },
  recentChanges: [
    {
      date: "6. 8. 2026",
      title: "Obrubníkové základy",
      body: "Plná parta ve složení Ivan, Tatíno a Vasil pracovala na tvorbě obrubníkových základů. Den je vedený jako 100 % náš projekt.",
      projectIds: ["paved-areas"],
    },
    {
      date: "3. 8. 2026",
      title: "Štěrk pod vířivku",
      body: "Tatíno a Vasil pokračovali ve výkopech pod vířivkou, navezli a rozprostřeli štěrk 0/32 a připravili podklad pro hutnění. Materiál štěrk 0/32 za 4 900 Kč je 100 % náš náklad.",
      projectIds: ["hot-tub", "paved-areas"],
    },
    {
      date: "27. 7. 2026",
      title: "Vířivka a světlo v šatně",
      body: "Plná parta pokračovala ve výkopech pro vířivku, odvezla zeminu, manipulovala s dlažbou a nainstalovala světlo v šatně. Den je 100 % náš projekt.",
      projectIds: ["hot-tub", "lighting"],
    },
    {
      date: "25. 7. 2026",
      title: "Štěrkové lože pro vířivku a BOMMA",
      body: "Plná parta připravila výkop pro štěrkové lože a plochu pro budoucí dlažbu pod vířivkou. Současně bylo instalováno závěsné světlo BOMMA v kuchyni.",
      projectIds: ["hot-tub", "lighting"],
    },
    {
      date: "21. 7. 2026",
      title: "Elektro rozvody a příprava vířivky",
      body: "Plná parta pokračovala ve výkopech elektroinstalace, pokládce husích krků a připravila terén pro budoucí vířivku. Den je 100 % náš projekt.",
      projectIds: ["electricity", "hot-tub"],
    },
    {
      date: "17. 7. 2026",
      title: "Společný projekt uzavřen, elektřina zahájena",
      body: "Driveway zídka, západní zídka pod WPC a společné práce s Löffelmanovými byly dokončeny. Následně začala první elektrotrasa směrem k východnímu plotu.",
      projectIds: ["shared-loffelman", "driveway-wall", "garden-partition", "electricity"],
    },
    {
      date: "15. 7. 2026",
      title: "Omítky a sdílené účtenky",
      body: "Doplněny práce do 15. 7. a T+L účtenky za omítku, stříšky a navazující materiál v součtu 7 639 Kč.",
      projectIds: ["driveway-wall", "garden-partition"],
    },
    {
      date: "11. 7. 2026",
      title: "Zídky připraveny na finální omítku",
      body: "Na driveway zídce i západní zídce pod WPC byly nalepeny stříšky a provedena penetrace. Celý den je sdílený 50 / 50 s Löffelmanovými.",
      projectIds: ["driveway-wall", "garden-partition"],
    },
    {
      date: "8. 7. 2026",
      title: "Tapety dokončeny",
      body: "Dokončena ložnice. Součástí dne byla i práce výhradně pro Löffelmanovy mimo naše a sdílené náklady.",
      projectIds: ["wallpaper"],
    },
    {
      date: "7. 7. 2026",
      title: "Příprava na finální omítku",
      body: "Dokončena armovací stěrka na driveway zídce a podezdívce pod WPC jako sdílená práce s Löffelmanovými.",
      projectIds: ["driveway-wall", "garden-partition"],
    },
    {
      date: "4. 7. 2026",
      title: "Východní plot dokončen",
      body: "Po montáži panelů a podhrabových desek byl východní plot kompletně dokončen.",
      projectIds: ["east-fence"],
    },
    {
      date: "4. 7. 2026",
      title: "Tapety v dětském pokoji",
      body: "Dětský pokoj byl hotový, ložnice tehdy čekala na dodání zbývající tapety.",
      projectIds: ["wallpaper"],
    },
  ],
  projectHub: {
    columns: [
      ["waiting", "⏳ Čeká"],
      ["progress", "🔨 Probíhá"],
      ["done", "✅ Hotovo"],
    ],
    items: [
      {
        id: "pergola",
        emoji: "🪵",
        title: "Pergola",
        status: "waiting",
        summary: "Rozpočet schválen, čeká termín realizace.",
        nextStep: "Doplnit termín realizace.",
        aliases: ["pergola"],
      },
      {
        id: "pool",
        emoji: "🏊",
        title: "Bazén",
        status: "waiting",
        summary: "Čeká budget a finální plán.",
        nextStep: "Doplnit finální rozpočet.",
        aliases: ["bazén", "bazen"],
      },
      {
        id: "garden-house",
        emoji: "🌳",
        title: "Zahradní domek",
        status: "waiting",
        summary: "Plánovaná navazující etapa.",
        nextStep: "Doplnit termín dlažby pod domek.",
        aliases: ["zahradní domek", "zahradni domek", "domek"],
      },
      {
        id: "electricity",
        emoji: "⚡",
        title: "Rozvody elektřiny",
        status: "progress",
        summary: "Zahájeno 17. 7.; 21. 7. pokračovaly výkopy elektroinstalace a pokládka husích krků.",
        nextStep: "Navázat další etapou rozvodů elektřiny.",
        aliases: ["elektro", "rozvody elektřiny", "rozvody elektriny", "nabíjení", "nabijeni", "11 kW"],
      },
      {
        id: "shared-loffelman",
        emoji: "🤝",
        title: "Společný projekt s Löffelmanovými",
        status: "done",
        summary: "Uzavřený celek: driveway zídka, západní zídka pod WPC, sdílené materiály a práce. Dokončeno 17. 7. 2026.",
        nextStep: null,
        sourceTitle: "Společné práce s Löffelmanovými",
        archivedProjectIds: ["driveway-wall", "garden-partition"],
        aliases: ["společný projekt", "spolecny projekt", "společné práce", "spolecne prace", "löffelmanovi", "loffelmanovi", "driveway", "driveway zídka", "driveway zidka", "zahradní přepažení", "zahradni prepazeni", "západní zídka", "zapadni zidka", "wpc", "podezdívka", "podezdivka"],
      },
      {
        id: "hot-tub",
        emoji: "♨️",
        title: "Vířivka",
        status: "progress",
        summary: "Probíhá příprava podkladu: výkopy, štěrk 0/32, plocha pro dlažbu a příprava pro hutnění.",
        nextStep: "Zhutnit podklad a navázat další vrstvou podle technického plánu zpevněných ploch.",
        aliases: ["vířivka", "virivka", "whirlpool", "spa", "štěrk", "sterk", "zpevněné plochy", "zpevnene plochy"],
      },
      {
        id: "paved-areas",
        emoji: "🪨",
        title: "Výkopové práce pod zpevněné plochy",
        status: "progress",
        summary: "Technický plán pro plochy pod vířivkou, terasou, domkem, pergolou a navazující dlažbou. Aktuálně probíhají výkopy, štěrkové vrstvy a tvorba obrubníkových základů.",
        nextStep: "Pokračovat obrubníkovými základy, doplnit další dodávky štěrku podle skutečné potřeby a připravit vrstvy.",
        sourceTitle: "Výkopové práce pod zpevněné plochy",
        aliases: ["zpevněné plochy", "zpevnene plochy", "výkopové práce", "vykopove prace", "štěrk", "sterk", "0/32", "4/8", "hutnění", "hutneni", "obrubníky", "obrubniky", "základy", "zaklady", "vířivka", "virivka", "terasa", "domek", "pergola"],
      },
      {
        id: "loffelman-project",
        emoji: "🏡",
        title: "Projekt Löffelmanových",
        status: "done",
        summary: "Dlažba cca 2 m² uhrazená Trantinovými, 100 % náklad Löffelmanových.",
        nextStep: null,
        aliases: ["loffelman", "löffelman", "sousedé", "sousede", "dlažba u loffelmanových", "dlazba u loffelmanovych"],
      },
      {
        id: "wallpaper",
        emoji: "🏠",
        title: "Tapety",
        status: "done",
        summary: "Projekt Tapety dokončen 8. 7. 2026.",
        nextStep: null,
        aliases: ["tapety", "tapeta", "dětský pokoj", "detsky pokoj", "ložnice", "loznice"],
      },
      {
        id: "lighting",
        emoji: "💡",
        title: "Osvětlení",
        status: "progress",
        summary: "Závěsné světlo BOMMA v kuchyni a světlo v šatně jsou nainstalované.",
        nextStep: "Dokončit zbývající světla v chodbách a LED track.",
        aliases: ["osvětlení", "osvetleni", "světlo", "svetlo", "led", "interiér", "interier", "bomma", "šatna", "satna"],
      },
      {
        id: "south-fence",
        emoji: "🧱",
        title: "Jižní plot",
        status: "done",
        summary: "Dokončen 26. 6. 2026 bez podhrabovek.",
        nextStep: null,
        aliases: ["jižní plot", "jizni plot"],
      },
      {
        id: "east-fence",
        emoji: "🧱",
        title: "Východní plot",
        status: "done",
        summary: "Kompletně dokončen 4. 7. 2026.",
        nextStep: null,
        aliases: ["východní plot", "vychodni plot"],
      },
      {
        id: "railing",
        emoji: "🧱",
        title: "Zábradlí",
        status: "done",
        summary: "Realizace dokončena, namontováno a uhrazeno.",
        nextStep: null,
        aliases: ["zábradlí", "zabradli"],
      },
      {
        id: "mirrors",
        emoji: "🪞",
        title: "Zrcadla",
        status: "done",
        summary: "Montáž dokončena 1. 7. 2026.",
        nextStep: null,
        aliases: ["zrcadla", "zrcadlo"],
      },
    ],
  },
  workCosts: {
    note:
      "Standardní denní sazba plné party: 9 000 Kč / den, dvoučlenné party 6 000 Kč / den. Evidováno 195 750 Kč práce k úhradě Ivanově partě. Dne 8. 7. je z celkových 3 750 Kč jen 2 250 Kč v našem / sdíleném rozpočtu; dalších 1 500 Kč je 100 % náklad Loffelmanových hrazený námi. Dne 17. 7. pracovala plná parta na sdíleném projektu 50 / 50, dny 21., 25., 27. 7. a 6. 8. jsou 100 % náš projekt a 3. 8. dvoučlenná parta také 100 % náš projekt.",
    cards: [
      ["Celkem", "good", "Veškerá práce k úhradě", "195 750 Kč"],
      ["Společný projekt", "split", "Práce k dělení", "76 575 Kč"],
      ["Náš podíl", "split", "Podíl na sdílené práci", "38 287,50 Kč"],
      ["Podíl sousedů", "split", "Loffelmanovi", "38 287,50 Kč"],
      ["Náš projekt", "good", "Samostatná práce", "117 675 Kč"],
      ["Jen Loffelmanovi", "wait", "100 % jejich práce", "1 500 Kč"],
      ["Reálně naše", "good", "Náš náklad práce", "155 962,50 Kč"],
    ],
    headers: ["Datum", "Celkem k úhradě", "Společný projekt", "Náš projekt", "100 % Loffelmanovi", "Náš podíl společně", "Podíl sousedů"],
    rows: [
      ["17. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
      ["18. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
      ["19. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
      ["22. 6.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
      ["23. 6.", "9 000 Kč", "4 500 Kč", "4 500 Kč", "0 Kč", "2 250 Kč", "2 250 Kč"],
      ["24. 6.", "9 000 Kč", "6 750 Kč", "2 250 Kč", "0 Kč", "3 375 Kč", "3 375 Kč"],
      ["25. 6.", "9 000 Kč", "6 750 Kč", "2 250 Kč", "0 Kč", "3 375 Kč", "3 375 Kč"],
      ["26. 6.", "9 000 Kč", "4 500 Kč", "4 500 Kč", "0 Kč", "2 250 Kč", "2 250 Kč"],
      ["29. 6.", "6 000 Kč", "1 200 Kč", "4 800 Kč", "0 Kč", "600 Kč", "600 Kč"],
      ["30. 6.", "6 000 Kč", "6 000 Kč", "0 Kč", "0 Kč", "3 000 Kč", "3 000 Kč"],
      ["1. 7.", "9 000 Kč", "6 750 Kč", "2 250 Kč", "0 Kč", "3 375 Kč", "3 375 Kč"],
      ["2. 7.", "9 000 Kč", "9 000 Kč", "0 Kč", "0 Kč", "4 500 Kč", "4 500 Kč"],
      ["3. 7.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
      ["4. 7.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
      ["7. 7.", "6 000 Kč", "6 000 Kč", "0 Kč", "0 Kč", "3 000 Kč", "3 000 Kč"],
      ["8. 7.", "3 750 Kč", "1 125 Kč", "1 125 Kč", "1 500 Kč", "562,50 Kč", "562,50 Kč"],
      ["11. 7.", "6 000 Kč", "6 000 Kč", "0 Kč", "0 Kč", "3 000 Kč", "3 000 Kč"],
      ["15. 7.", "9 000 Kč", "9 000 Kč", "0 Kč", "0 Kč", "4 500 Kč", "4 500 Kč"],
      ["17. 7.", "9 000 Kč", "9 000 Kč", "0 Kč", "0 Kč", "4 500 Kč", "4 500 Kč"],
      ["21. 7.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
      ["25. 7.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
      ["27. 7.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
      ["3. 8.", "6 000 Kč", "0 Kč", "6 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
      ["6. 8.", "9 000 Kč", "0 Kč", "9 000 Kč", "0 Kč", "0 Kč", "0 Kč"],
    ],
    total: ["Součet", "195 750 Kč", "76 575 Kč", "117 675 Kč", "1 500 Kč", "38 287,50 Kč", "38 287,50 Kč"],
  },
  worklog: {
    monthLabel: "Červen / červenec / srpen 2026",
    legend: [
      ["🟩", "Náš projekt"],
      ["🟦", "Společný projekt"],
      ["🟧", "Kombinovaný den"],
      ["💸", "Platba / vyrovnání"],
      ["⬜", "Nepracovalo se"],
    ],
    days: [
      { day: 1, type: "off", title: "Nepracovalo se" },
      { day: 2, type: "off", title: "Nepracovalo se" },
      { day: 3, type: "off", title: "Nepracovalo se" },
      { day: 4, type: "off", title: "Nepracovalo se" },
      { day: 5, type: "off", title: "Nepracovalo se" },
      { day: 6, type: "off", title: "Nepracovalo se" },
      { day: 7, type: "off", title: "Nepracovalo se" },
      { day: 8, type: "off", title: "Nepracovalo se" },
      { day: 9, type: "off", title: "Nepracovalo se" },
      { day: 10, type: "off", title: "Nepracovalo se" },
      { day: 11, type: "off", title: "Nepracovalo se" },
      { day: 12, type: "off", title: "Nepracovalo se" },
      { day: 13, type: "off", title: "Nepracovalo se" },
      { day: 14, type: "off", title: "Nepracovalo se" },
      { day: 15, type: "off", title: "Nepracovalo se" },
      { day: 16, type: "off", title: "Nepracovalo se" },
      {
        day: 17,
        type: "own",
        title: "Start prací",
        short: "Start",
        tooltip: "17.6. Start prací / Ivanova parta / 9 000 Kč",
        detail: {
          date: "17. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Start prací na zahradě"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Ivanova parta začala pracovat. Sazba dne 9 000 Kč.",
        },
      },
      {
        day: 18,
        type: "own",
        title: "Práce pokračují",
        short: "Práce",
        tooltip: "18.6. Práce pokračují / Ivanova parta / 9 000 Kč",
        detail: {
          date: "18. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Práce pokračují"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Celý den je vedený jako náš samostatný projekt.",
        },
      },
      {
        day: 19,
        type: "own",
        title: "Práce pokračují",
        short: "Práce",
        tooltip: "19.6. Práce pokračují / Ivanova parta / 9 000 Kč",
        detail: {
          date: "19. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Práce pokračují"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Celý den je vedený jako náš samostatný projekt.",
        },
      },
      { day: 20, type: "off", title: "Nepracovalo se" },
      { day: 21, type: "off", title: "Nepracovalo se" },
      {
        day: 22,
        type: "own",
        title: "Práce pokračují",
        short: "Práce",
        tooltip: "22.6. Práce pokračují / Ivanova parta / 9 000 Kč",
        detail: {
          date: "22. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Práce pokračují"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourCost: 9000 },
          projects: ["🏡 Náš zahradní projekt"],
          notes: "Celý den je vedený jako náš samostatný projekt.",
        },
      },
      {
        day: 23,
        type: "mixed",
        title: "Společný západní plot",
        short: "Plot",
        tooltip: "23.6. Společný západní plot / 50 % společné / 9 000 Kč",
        detail: {
          date: "23. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Společný západní plot", "Práce od 10:00 na hranici s Loffelmanovými"],
          finance: { total: 9000, ownPercent: 50, sharedPercent: 50, ownAmount: 4500, sharedAmount: 4500, ourSharedShare: 2250, neighborSharedShare: 2250, ourCost: 6750 },
          projects: ["🪵 Zahradní přepažení", "🏡 Náš zahradní projekt"],
          notes: "Sdílená práce cca 50 % dne.",
        },
      },
      {
        day: 24,
        type: "mixed",
        title: "Ztracené bednění",
        short: "Bednění",
        tooltip: "24.6. Ztracené bednění / 75 % společné / 9 000 Kč",
        detail: {
          date: "24. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Nákup, měření a zasazení ztraceného bednění", "Stržení jižního plotu"],
          finance: { total: 9000, ownPercent: 25, sharedPercent: 75, ownAmount: 2250, sharedAmount: 6750, ourSharedShare: 3375, neighborSharedShare: 3375, ourCost: 5625 },
          projects: ["🪵 Zahradní přepažení", "🧱 Ploty a zeď"],
          notes: "Cca 75 % dne společný projekt, 25 % náš samostatný projekt.",
        },
      },
      {
        day: 25,
        type: "mixed",
        title: "ROJA + betonáž",
        short: "Betonáž",
        tooltip: "25.6. ROJA + betonáž / 75 % společné / 9 000 Kč",
        detail: {
          date: "25. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Dorazily ROJA WPC desky a sloupky", "Betonáž"],
          finance: { total: 9000, ownPercent: 25, sharedPercent: 75, ownAmount: 2250, sharedAmount: 6750, ourSharedShare: 3375, neighborSharedShare: 3375, ourCost: 5625 },
          projects: ["🪵 Zahradní přepažení", "🧱 Ploty a zeď"],
          notes: "Cca 75 % dne společný projekt.",
        },
      },
      {
        day: 26,
        type: "mixed",
        title: "Jižní plot + WPC",
        short: "WPC",
        tooltip: "26.6. Jižní plot + WPC / 50 % společné / 9 000 Kč",
        detail: {
          date: "26. 6. 2026",
          workers: ["Ivanova parta"],
          done: ["Jižní plot dokončen bez podhrabovek", "WPC desky nahozeny"],
          finance: { total: 9000, ownPercent: 50, sharedPercent: 50, ownAmount: 4500, sharedAmount: 4500, ourSharedShare: 2250, neighborSharedShare: 2250, ourCost: 6750 },
          projects: ["🪵 Zahradní přepažení", "🧱 Ploty a zeď"],
          notes: "Zbývá omítnout. Použitá fasáda: Mistral omítka silikon 1,5H TB.",
        },
      },
      { day: 27, type: "off", title: "Nepracovalo se" },
      {
        day: 28,
        type: "off",
        title: "Zábradlí dokončeno a vyfakturováno",
        short: "Zábradlí",
        tooltip: "28.6. Zábradlí dokončeno a vyfakturováno / bez práce Ivanovy party",
        detail: {
          date: "28. 6. 2026",
          workers: [],
          done: ["Zábradlí dokončeno", "Faktura č. 26062801 zaevidována"],
          projects: ["🧱 Zábradlí"],
          notes: "Faktura od Petr Sedláček / AKTO na 80 109,12 Kč. Jde o 100 % soukromý náklad mimo vyúčtování s Loffelmanovými.",
        },
      },
      {
        day: 29,
        type: "mixed",
        title: "Nátěr perlinky na zídku",
        short: "Perlinka",
        tooltip: "29.6. Perlinka / 2 pracovníci / 6 000 Kč",
        detail: {
          date: "29. 6. 2026",
          workers: ["Ivan", "Tatíno"],
          done: ["Perlinka", "Zídka"],
          finance: { total: 6000, ownPercent: 80, sharedPercent: 20, ownAmount: 4800, sharedAmount: 1200, ourSharedShare: 600, neighborSharedShare: 600, ourCost: 5400 },
          projects: ["🪵 Zahradní přepažení"],
          notes: "Dělal se nátěr perlinky na zídku. Pracovali pouze Ivan a Tatíno, proto snížená sazba dne 6 000 Kč. 20 % času bylo na společném projektu a 80 % na našem samostatném projektu.",
        },
      },
      {
        day: 30,
        type: "shared",
        title: "Výkop základů + vyrovnání",
        short: "🚧 Výkop driveway zídky",
        tooltip: "30.6. Výkop základů pro driveway zídku / Vasil, Tatíno, Ivan / 6 000 Kč",
        detail: {
          date: "30. 6. 2026",
          workers: ["Vasil - celý den (8 h)", "Tatíno - celý den (8 h)", "Ivan - cca 1 hodina (výpomoc)"],
          done: ["Výkop základů pro driveway zídku", "Proběhlo částečné finanční vyrovnání s Ivanem", "Vyplaceno 72 000 Kč"],
          finance: { total: 6000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 6000, ourSharedShare: 3000, neighborSharedShare: 3000, ourCost: 3000, extraRows: [["Vyrovnání Ivanovi", "72 000 Kč"]] },
          projects: ["🚗 Driveway zídka", "👷 Práce Ivanovy party"],
          notes: "Práce dne 30. 6. patří celá do společného projektu s Lofflemanovými a dělí se 50 / 50. Náklad práce: 2 osoby x 3 000 Kč = 6 000 Kč. Ve stejný den proběhlo částečné finanční vyrovnání s Ivanem ve výši 72 000 Kč.",
        },
      },
      {
        id: "2026-07-01",
        day: 1,
        label: "1.7.",
        type: "mixed",
        selected: true,
        title: "Driveway zídka + tapety",
        short: "Driveway/Tapety",
        tooltip: "1.7. Driveway zídka 75 %, tapety 25 % / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "1. 7. 2026",
          workers: ["Ivan", "Vasil", "Tatíno"],
          done: ["Driveway zídka - 75 % dne", "Tapety - 25 % dne"],
          finance: { total: 9000, ownPercent: 25, sharedPercent: 75, ownAmount: 2250, sharedAmount: 6750, ourSharedShare: 3375, neighborSharedShare: 3375, ourCost: 5625 },
          projects: ["🚗 Driveway zídka", "🏠 Tapety"],
          notes: "Pracovala plná parta: Ivan, Vasil a Tatíno. 75 % dne patří do společného projektu Driveway zídka a dělí se 50 / 50 s Lofflemanovými. 25 % dne patří do našeho projektu Tapety a do společného vyúčtování nevstupuje.",
        },
      },
      {
        id: "2026-07-02",
        day: 2,
        label: "2.7.",
        type: "shared",
        title: "Driveway zídka",
        short: "Driveway",
        tooltip: "2.7. Driveway zídka / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "2. 7. 2026",
          workers: ["Ivan", "Vasil", "Tatíno"],
          done: ["Pokračovala realizace driveway zídky", "Celý den vedený jako společný projekt 50 / 50 s Lofflemanovými"],
          finance: { total: 9000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 9000, ourSharedShare: 4500, neighborSharedShare: 4500, ourCost: 4500 },
          projects: ["🚗 Driveway zídka"],
          notes: "Pracovala plná parta: Ivan, Vasil a Tatíno. Celý den patří do společného projektu Driveway zídka a dělí se 50 / 50 s Lofflemanovými.",
        },
      },
      {
        id: "2026-07-03",
        day: 3,
        label: "3.7.",
        type: "own",
        title: "Východní plot",
        short: "Plot",
        tooltip: "3.7. Východní plot / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "3. 7. 2026",
          workers: ["Ivan", "Vasil", "Tatíno"],
          done: ["Vrty pro sloupky", "Betonování sloupků", "Erekce / osazení plotových panelů", "Montáž plotu"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourSharedShare: 0, neighborSharedShare: 0, ourCost: 9000 },
          projects: ["🧱 Východní plot", "🧱 Ploty a zeď"],
          notes: "Pracovala plná parta: Ivan, Vasil a Tatíno. Celý den se pracovalo pouze na našem projektu Východní plot. Náklad práce: 3 osoby x 3 000 Kč = 9 000 Kč. Práce na východním plotu výrazně pokročily a navazující dokončení proběhlo 4. 7. Nejde o sdílený projekt s Loffelmanovými.",
        },
      },
      {
        id: "2026-07-04",
        day: 4,
        label: "4.7.",
        type: "mixed",
        title: "Východní plot + tapety",
        short: "Plot/Tapety",
        tooltip: "4.7. Východní plot 75 %, tapety 25 % / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "4. 7. 2026",
          workers: ["Ivan", "Vasil", "Tatíno"],
          done: ["Východní plot byl kompletně dokončen", "Montáž podhrabových desek dokončena", "Tapety - dětský pokoj dokončen", "Tapety - ložnice navázala dokončením 8. 7.", "Podhrabové desky a příslušenství za 1 859 Kč uhrazeny a dodány"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourSharedShare: 0, neighborSharedShare: 0, ourCost: 9000, extraRows: [["Východní plot 75 %", "6 750 Kč"], ["Tapety 25 %", "2 250 Kč"], ["Materiál - podhrabové desky a příslušenství", "1 859 Kč"]] },
          projects: ["🧱 Východní plot", "🧱 Ploty a zeď", "🏠 Tapety"],
          notes: "Pracovala plná parta: Ivan, Vasil a Tatíno celý pracovní den. Náklad práce: 3 osoby x 3 000 Kč = 9 000 Kč. Práce se dělí mezi naše projekty: 75 % východní plot = 6 750 Kč a 25 % tapety = 2 250 Kč. Východní plot byl kompletně dokončen. Materiál podhrabové desky a příslušenství je dle účtenky Ploty Dobrý & Urbánek uhrazený a dodaný za 1 859 Kč. Práce i materiál jsou 100 % náš náklad mimo vyúčtování s Loffelmanovými.",
        },
      },
      { id: "2026-07-05", day: 5, label: "5.7.", type: "off", title: "Nepracovalo se" },
      { id: "2026-07-06", day: 6, label: "6.7.", type: "off", title: "Nepracovalo se" },
      {
        id: "2026-07-07",
        day: 7,
        label: "7.7.",
        type: "shared",
        title: "Armovací stěrka",
        short: "Stěrka",
        tooltip: "7.7. Armovací stěrka a příprava na finální omítku / Tatíno, Vasil / 6 000 Kč",
        detail: {
          date: "7. 7. 2026",
          workers: ["Tatíno", "Vasil"],
          done: ["Armovací stěrka na driveway zídce", "Armovací stěrka na podezdívce pod WPC", "Příprava obou zídek na finální silikonovou omítku"],
          finance: { total: 6000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 6000, ourSharedShare: 3000, neighborSharedShare: 3000, ourCost: 3000 },
          projects: ["🚗 Driveway zídka", "🪵 Zahradní přepažení"],
          notes: "Ivan tento den nepracoval. Celý den pracovali Tatíno a Vasil, sazba dne je 2 osoby x 3 000 Kč = 6 000 Kč. Nejedná se o finální omítku. Proběhla armovací vrstva jako podklad pod finální silikonovou omítku Mistral silikon 1,5H TB. Práce je sdílený náklad s Loffelmanovými a dělí se 50 / 50.",
        },
      },
      {
        id: "2026-07-08",
        day: 8,
        label: "8.7.",
        type: "mixed",
        title: "Tapety + zídka + sousedé",
        short: "Tapety/Zídka",
        tooltip: "8.7. Tapety, společná zídka a dlažba u Loffelmanových / Tatíno, Vasil / 5 h",
        detail: {
          date: "8. 7. 2026",
          workers: ["Tatíno", "Vasil"],
          done: ["Tapety - dokončení ložnice", "Společná zídka - navazující práce", "Dlažba u Loffelmanových - finalizace cca 2 m²"],
          finance: {
            grossTotal: 3750,
            total: 2250,
            ownPercent: 50,
            sharedPercent: 50,
            ownAmount: 1125,
            sharedAmount: 1125,
            loffelmanAmount: 1500,
            ourSharedShare: 562.5,
            neighborSharedShare: 562.5,
            ourCost: 1687.5,
            extraRows: [["🏡 Projekt Loffelmanových", "Pokládka dlažby cca 2 m² / 2 h / 1 500 Kč / uhrazeno Trantinovými / 100 % náklad Loffelmanových"], ["🪨 Materiál dlažby Loffelmanových", "cca 2 m² x 700 Kč = 1 400 Kč / 100 % náklad Loffelmanových"], ["Pohledávka za Loffelmanovými", "2 900 Kč"], ["Tapety 100 % náš projekt", "1,5 h / 1 125 Kč"], ["Společná zídka 50 / 50", "1,5 h / 1 125 Kč"]],
          },
          projects: ["🏠 Tapety", "🪵 Zahradní přepažení", "🏡 Projekt Loffelmanových"],
          notes: "Tatíno a Vasil pracovali 5 hodin, tedy 10 člověkohodin. Sazba odpovídá 750 Kč / hodina celkem za dvojici, celkem k úhradě Ivanově partě 3 750 Kč. Rozdělení dne: 1,5 h Tapety 1 125 Kč jako 100 % náš projekt, 1,5 h společná zídka 1 125 Kč jako 50 / 50 a 2 h pokládka dlažby u Loffelmanových 1 500 Kč jako 100 % jejich projekt. Část práce na dlažbě Löffelmanových je evidována jako pohledávka za Löffelmanovými, nikoli jako náš nebo sdílený náklad. Dlažba u Löffelmanových byla uhrazena Trantinovými a zakládá pohledávku: práce 1 500 Kč + materiál 1 400 Kč = 2 900 Kč.",
        },
      },
      { id: "2026-07-09", day: 9, label: "9.7.", type: "off", title: "Nepracovalo se" },
      { id: "2026-07-10", day: 10, label: "10.7.", type: "off", title: "Nepracovalo se" },
      {
        id: "2026-07-11",
        day: 11,
        label: "11.7.",
        type: "shared",
        title: "Stříšky a penetrace",
        short: "Zídky",
        tooltip: "11.7. Stříšky a penetrace zídek / Tatíno, Vasil / 6 000 Kč",
        detail: {
          date: "11. 7. 2026",
          workers: ["Tatíno", "Vasil"],
          done: ["Driveway zídka - lepení stříšek", "Driveway zídka - penetrace před finální omítkou", "Západní zídka pod WPC - lepení stříšek", "Západní zídka pod WPC - penetrace", "Západní zídka pod WPC - řezání stříšek podle potřebných rozměrů"],
          finance: { total: 6000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 6000, ourSharedShare: 3000, neighborSharedShare: 3000, ourCost: 3000 },
          projects: ["🚗 Driveway zídka", "🪵 Zahradní přepažení"],
          notes: "Ivan tento den nepracoval. Pracovali Tatíno a Vasil, standardní den dvoučlenné party za 6 000 Kč. Celý pracovní den spadal do společného projektu s Loffelmanovými a dělí se 50 / 50.",
        },
      },
      {
        id: "2026-07-14",
        day: 14,
        label: "14.7.",
        type: "off",
        title: "Nepracovalo se",
        tooltip: "14.7. Nepracovalo se / bez nákladu práce",
      },
      {
        id: "2026-07-15",
        day: 15,
        label: "15.7.",
        type: "shared",
        title: "Omítky a plotová pole",
        short: "Omítky/Pole",
        tooltip: "15.7. Dokončovací vrstvy a montáž plotových polí / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "15. 7. 2026",
          workers: ["Ivan", "Vasil", "Tatíno"],
          done: ["Omítka / dokončovací vrstvy na driveway zídce", "Omítka / dokončovací vrstvy na WPC západním plotu", "Montáž plotového pole / plotových polí"],
          finance: { total: 9000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 9000, ourSharedShare: 4500, neighborSharedShare: 4500, ourCost: 4500 },
          projects: ["🚗 Driveway zídka", "🪵 Zahradní přepažení"],
          notes: "Pracovala plná parta: Ivan, Vasil a Tatíno. Denní sazba: 3 osoby x 3 000 Kč = 9 000 Kč. Podle aktuální projektové evidence jde o společnou práci související s driveway zídkou a WPC západním plotem, dělení 50 / 50 s Loffelmanovými.",
        },
      },
      {
        id: "2026-07-17",
        day: 17,
        label: "17.7.",
        type: "shared",
        title: "Driveway hotovo + elektro",
        short: "Driveway/Elektro",
        tooltip: "17.7. Driveway zídka dokončena a zahájeny rozvody elektřiny / Ivan, Vasil, Tatíno / 9 000 Kč",
        detail: {
          date: "17. 7. 2026",
          workers: ["Ivan", "Tatíno", "Vasil"],
          done: ["Driveway zídka - kompletní dokončení společného projektu", "Dokončovací práce převážně na straně Loffelmanových", "Rozvody elektřiny - vykopána první trasa elektroinstalace", "Výkop směrem k východnímu plotu"],
          finance: { total: 9000, ownPercent: 0, sharedPercent: 100, ownAmount: 0, sharedAmount: 9000, ourSharedShare: 4500, neighborSharedShare: 4500, ourCost: 4500, extraRows: [["Driveway zídka", "sdílený projekt 50 / 50, nevzniká samostatná pohledávka za Loffelmanovými"], ["Rozvody elektřiny", "zahájena nová etapa, vykopána první elektrotrasa směrem k východnímu plotu"]] },
          projects: ["🚗 Driveway zídka", "⚡ Rozvody elektřiny"],
          notes: "Pracovala plná parta: Ivan, Tatíno a Vasil. Denní sazba: 3 osoby x 3 000 Kč = 9 000 Kč. Driveway zídka byla kompletně dokončena; dokončovací práce probíhaly převážně na straně Loffelmanových a Ivan zde odpracoval přibližně 3,5 hodiny. Přesto jde o sdílený projekt 50 / 50, nikoli o projekt Loffelmanových, takže práce navyšuje společný základ a dělí se rovným dílem. Po dokončení zídky byla zahájena etapa Rozvody elektřiny a vykopána první trasa směrem k východnímu plotu.",
        },
      },
      {
        id: "2026-07-21",
        day: 21,
        label: "21.7.",
        type: "own",
        title: "Elektro + vířivka",
        short: "Elektro/Vířivka",
        tooltip: "21.7. Rozvody elektřiny a příprava terénu pro vířivku / Ivan, Tatíno, Vasil / 9 000 Kč",
        detail: {
          date: "21. 7. 2026",
          workers: ["Ivan", "Tatíno", "Vasil"],
          done: ["Rozvody elektřiny - pokračování výkopů elektroinstalace", "Rozvody elektřiny - pokládka husích krků", "Vířivka - terénní úpravy pro budoucí umístění"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourSharedShare: 0, neighborSharedShare: 0, ourCost: 9000, extraRows: [["Rozvody elektřiny", "pokračování výkopů a pokládka husích krků"], ["Vířivka", "zahájena příprava terénu"]] },
          projects: ["⚡ Rozvody elektřiny", "♨️ Vířivka"],
          notes: "Pracovala plná parta: Ivan, Tatíno a Vasil celý pracovní den. Denní sazba: 3 osoby x 3 000 Kč = 9 000 Kč. Jedná se o 100 % náš projekt; práce se nezapočítává do sdíleného projektu ani do projektu Loffelmanových.",
        },
      },
      {
        id: "2026-07-25",
        day: 25,
        label: "25.7.",
        type: "own",
        title: "Vířivka + BOMMA",
        short: "Vířivka/BOMMA",
        tooltip: "25.7. Výkop pro štěrkové lože a instalace světla BOMMA / Ivan, Tatíno, Vasil / 9 000 Kč",
        detail: {
          date: "25. 7. 2026",
          workers: ["Ivan", "Tatíno", "Vasil"],
          done: ["Vířivka - výkop pro štěrkové lože", "Vířivka - příprava plochy pro budoucí dlažbu pod vířivkou", "Osvětlení - instalace závěsného světla BOMMA v kuchyni"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourSharedShare: 0, neighborSharedShare: 0, ourCost: 9000, extraRows: [["Vířivka", "výkop pro štěrkové lože a příprava plochy pro dlažbu"], ["Osvětlení", "instalace závěsného světla BOMMA v kuchyni"]] },
          projects: ["♨️ Vířivka", "💡 Osvětlení"],
          notes: "Pracovala plná parta: Ivan, Tatíno a Vasil celý pracovní den. Denní sazba: 3 osoby x 3 000 Kč = 9 000 Kč. Jedná se o 100 % náš projekt; práce se nezapočítává do sdíleného projektu ani do projektu Loffelmanových.",
        },
      },
      {
        id: "2026-07-27",
        day: 27,
        label: "27.7.",
        type: "own",
        title: "Vířivka + šatna",
        short: "Vířivka/Šatna",
        tooltip: "27.7. Výkopy, odvoz zeminy, manipulace s dlažbou a světlo v šatně / Ivan, Tatíno, Vasil / 9 000 Kč",
        detail: {
          date: "27. 7. 2026",
          workers: ["Ivan", "Tatíno", "Vasil"],
          done: ["Vířivka - pokračování výkopových prací", "Vířivka - odvoz vytěžené zeminy", "Vířivka - nakládka dlažby", "Vířivka - vykládka dlažby", "Osvětlení - instalace světla v šatně"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourSharedShare: 0, neighborSharedShare: 0, ourCost: 9000, extraRows: [["Vířivka", "pokračování výkopů, odvoz zeminy a manipulace s dlažbou"], ["Materiál - dlažba BAUHAUS", "20 189,40 Kč / uhrazeno námi / účtenka IMG_8699.JPG"], ["Osvětlení", "instalace světla v šatně"]] },
          projects: ["♨️ Vířivka", "💡 Osvětlení"],
          notes: "Pracovala plná parta: Ivan, Tatíno a Vasil celý pracovní den. Denní sazba: 3 osoby x 3 000 Kč = 9 000 Kč. Jedná se o 100 % náš projekt; práce se nezapočítává do sdíleného projektu ani do projektu Loffelmanových. Ve stejný den byla uhrazena dlažba BAUHAUS k vířivce za 20 189,40 Kč.",
        },
      },
      {
        id: "2026-08-03",
        day: 3,
        label: "3.8.",
        type: "own",
        title: "Štěrk pod vířivku",
        short: "Štěrk/Vířivka",
        tooltip: "3.8. Výkopy a štěrk 0/32 pod vířivku / Tatíno, Vasil / 6 000 Kč",
        detail: {
          date: "3. 8. 2026",
          workers: ["Tatíno", "Vasil"],
          done: ["Vířivka - pokračování výkopových prací pod budoucí vířivkou", "Vířivka - navezení a rozprostření štěrku 0/32", "Vířivka - příprava podkladu pro následné hutnění"],
          finance: { total: 6000, ownPercent: 100, sharedPercent: 0, ownAmount: 6000, sharedAmount: 0, ourSharedShare: 0, neighborSharedShare: 0, ourCost: 6000, extraRows: [["Vířivka", "pokračování výkopů, štěrk 0/32 a příprava pro hutnění"], ["Materiál - štěrk 0/32", "4 900 Kč / 100 % náš projekt / možné další dodávky budou doplněny později"], ["Zpevněné plochy", "první navážka štěrku pro budoucí podklad pod vířivku"]] },
          projects: ["♨️ Vířivka", "🪨 Výkopové práce pod zpevněné plochy"],
          notes: "Pracovala dvoučlenná parta: Tatíno a Vasil. Denní sazba: 2 osoby x 3 000 Kč = 6 000 Kč. Jedná se o 100 % náš projekt; práce ani materiál se nezapočítávají do sdíleného projektu ani do projektu Loffelmanových. Materiál štěrk 0/32 je zaevidovaný za 4 900 Kč a cena bude později doplněna o případné další dodávky štěrku, pokud budou potřeba.",
        },
      },
      {
        id: "2026-08-06",
        day: 6,
        label: "6.8.",
        type: "own",
        title: "Obrubníkové základy",
        short: "Obrubníky",
        tooltip: "6.8. Tvorba obrubníkových základů / Ivan, Tatíno, Vasil / 9 000 Kč",
        detail: {
          date: "6. 8. 2026",
          workers: ["Ivan", "Tatíno", "Vasil"],
          done: ["Tvorba obrubníkových základů"],
          finance: { total: 9000, ownPercent: 100, sharedPercent: 0, ownAmount: 9000, sharedAmount: 0, ourSharedShare: 0, neighborSharedShare: 0, ourCost: 9000, extraRows: [["Zpevněné plochy", "tvorba obrubníkových základů"]] },
          projects: ["🪨 Výkopové práce pod zpevněné plochy"],
          notes: "Pracovala plná parta: Ivan, Tatíno a Vasil. Denní sazba: 3 osoby x 3 000 Kč = 9 000 Kč. Jedná se o 100 % náš projekt; práce se nezapočítává do sdíleného projektu ani do projektu Loffelmanových. Ivanovi bylo předáno 10 000 Kč v hotovosti. Zatím neevidovat jako účetní pohyb; pouze poznámka pro budoucí vyrovnání závazků.",
        },
      },
    ],
  },
  settlement: {
    intro:
      "Průběžný výpis položek, ze kterých vzniká částka k úhradě od Lofflemanových. Řádky 50 / 50 ukazují jejich polovinu, řádky 100 % Loffelmanovi vstupují celé. Jméno Loffleman označuje sousedy; projektová položka se nově uzavírá jako Západní zídka pod WPC.",
    cards: [
      ["Materiál 50 / 50", "split", "🪵 WPC desky + sloupky + příslušenství", "37 669 Kč", "Náš podíl: 18 834,50 Kč\nPodíl Lofflemanových: 18 834,50 Kč"],
      ["Materiál 50 / 50", "split", "🚗 Hliníkové plotové pole driveway", "14 721 Kč", "Náš podíl: 7 360,50 Kč\nPodíl Lofflemanových: 7 360,50 Kč"],
      ["Materiál 50 / 50", "split", "🧱 Ztracené bednění a beton", "12 282 Kč", "Projekt: Driveway zídka\nNáš podíl: 6 141 Kč\nPodíl Lofflemanových: 6 141 Kč"],
      ["Materiál 50 / 50", "split", "🧱 OBI materiál k přepažení", "12 964 Kč", "Náš podíl: 6 482 Kč\nPodíl Lofflemanových: 6 482 Kč"],
      ["Materiál 50 / 50", "split", "🎨 Omítka, stříšky a lišty", "7 639 Kč", "Náš podíl: 3 819,50 Kč\nPodíl Lofflemanových: 3 819,50 Kč"],
      ["Materiál 50 / 50", "split", "🧾 T+L doplňková účtenka", "432 Kč", "Náš podíl: 216 Kč\nPodíl Lofflemanových: 216 Kč"],
      ["Práce 50 / 50", "split", "👷 Sdílená práce 23. 6.-17. 7.", "76 575 Kč", "Náš podíl: 38 287,50 Kč\nPodíl Lofflemanových: 38 287,50 Kč"],
      ["Známý základ", "good", "💰 Aktuálně známé sdílené náklady", "162 282 Kč", "Náš podíl: 81 141 Kč\nPodíl Lofflemanových: 81 141 Kč"],
      ["Pohledávka", "wait", "🏡 Pohledávka za Loffelmanovými", "2 900 Kč", "Dlažba u Loffelmanových cca 2 m²: práce 1 500 Kč + materiál 1 400 Kč. Uhrazeno Trantinovými, 100 % náklad Loffelmanových, mimo 50 / 50 základ."],
    ],
    headers: ["Položka", "👷 Parta", "Celkem", "Dělení", "Náš čistý podíl", "K úhradě od Lofflemanových", "Doklad / stav"],
    rows: [
      ["🪵 WPC desky + sloupky + příslušenství", "—", "37 669 Kč", "50 / 50", "18 834,50 Kč", "18 834,50 Kč", { badge: "Doklad doplnit", tone: "wait", title: "Částka je evidovaná, ale v assets zatím není přímý soubor účtenky / objednávky." }],
      ["🚗 Hliníkové plotové pole driveway", "—", "14 721 Kč", "50 / 50", "7 360,50 Kč", "7 360,50 Kč", { badge: "Doklad doplnit", tone: "wait", title: "Částka je evidovaná, ale v assets zatím není přímý soubor účtenky / objednávky." }],
      ["🧱 Ztracené bednění a beton - Driveway zídka", "—", "12 282 Kč", "50 / 50", "6 141 Kč", "6 141 Kč", { badge: "Účtenky", tone: "good", title: "Zaplaceno námi. T+L účtenky, redukce na vozík vyřazeny.", links: [{ label: "IMG_8228 ↗", href: "assets/receipts/IMG_8228.JPG" }, { label: "IMG_8250 ↗", href: "assets/receipts/IMG_8250.JPG" }] }],
      ["🧱 OBI materiál k přepažení - účtenky ve várkách", "—", "12 964 Kč", "50 / 50", "6 482 Kč", "6 482 Kč", { badge: "Účtenky", tone: "good", title: "Zaplaceno námi.", links: [{ label: "IMG_8198 ↗", href: "assets/receipts/IMG_8198.JPG" }, { label: "IMG_8199 ↗", href: "assets/receipts/IMG_8199.JPG" }, { label: "IMG_8200 ↗", href: "assets/receipts/IMG_8200.JPG" }, { label: "IMG_8201 ↗", href: "assets/receipts/IMG_8201.JPG" }] }],
      ["🎨 Materiál omítka a lišty - driveway + WPC", "—", "7 639 Kč", "50 / 50", "3 819,50 Kč", "3 819,50 Kč", { badge: "Účtenka", tone: "good", title: "Zaplaceno námi. Otevřít účtenku IMG_8601.JPG.", links: [{ label: "IMG_8601 ↗", href: "assets/receipts/IMG_8601.JPG" }] }],
      ["🧾 T+L doplňková účtenka", "—", "432 Kč", "50 / 50", "216 Kč", "216 Kč", { badge: "Účtenka", tone: "good", title: "Zaevidováno. Otevřít účtenku IMG_8603.JPG.", links: [{ label: "IMG_8603 ↗", href: "assets/receipts/IMG_8603.JPG" }] }],
      ["👷 Práce 23. 6. - sdílená část 50 % dne", { party: "👷×2", title: "2 osoby Ivanovy party" }, "4 500 Kč", "50 / 50", "2 250 Kč", "2 250 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 24. 6. - sdílená část 75 % dne", { party: "👷×3", title: "3 osoby Ivanovy party" }, "6 750 Kč", "50 / 50", "3 375 Kč", "3 375 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 25. 6. - sdílená část 75 % dne", { party: "👷×3", title: "3 osoby Ivanovy party" }, "6 750 Kč", "50 / 50", "3 375 Kč", "3 375 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 26. 6. - sdílená část 50 % dne", { party: "👷×2", title: "2 osoby Ivanovy party" }, "4 500 Kč", "50 / 50", "2 250 Kč", "2 250 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 29. 6. - sdílená část 20 % dne", { party: "👷×2", title: "2 osoby Ivanovy party" }, "1 200 Kč", "50 / 50", "600 Kč", "600 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 30. 6. - výkop driveway zídky", { party: "👷×2", title: "2 osoby Ivanovy party" }, "6 000 Kč", "50 / 50", "3 000 Kč", "3 000 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 1. 7. - driveway zídka 75 % dne", { party: "👷×3", title: "3 osoby Ivanovy party" }, "6 750 Kč", "50 / 50", "3 375 Kč", "3 375 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 2. 7. - driveway zídka", { party: "👷×3", title: "3 osoby Ivanovy party" }, "9 000 Kč", "50 / 50", "4 500 Kč", "4 500 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 7. 7. - armovací stěrka a příprava na omítku", { party: "👷×2", title: "2 osoby Ivanovy party" }, "6 000 Kč", "50 / 50", "3 000 Kč", "3 000 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 8. 7. - společná zídka 1,5 h", { party: "👷×2", title: "2 osoby Ivanovy party" }, "1 125 Kč", "50 / 50", "562,50 Kč", "562,50 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená část dne, dlažba Loffelmanových je vedena mimo 50 / 50." }],
      ["🏡 Pokládka dlažby u Löfflemanů", { party: "👷×2", title: "2 osoby Ivanovy party" }, "1 500 Kč", "100 % Loffelmanovi", "0 Kč", "1 500 Kč", { badge: "Pohledávka", tone: "wait", title: "100 % náklad Loffelmanových uhrazený Trantinovými. Nezapočítává se do společného základu 50 / 50." }],
      ["🪨 Materiál dlažby Loffelmanových cca 2 m²", "—", "1 400 Kč", "100 % Loffelmanovi", "0 Kč", "1 400 Kč", { badge: "Odvozeno", tone: "wait", title: "Dopočteno z dlažby 14 m²: cca 2 m² × 700 Kč. 100 % náklad Loffelmanových, mimo společný základ 50 / 50." }],
      ["👷 Práce 11. 7. - stříšky a penetrace zídek", { party: "👷×2", title: "2 osoby Ivanovy party" }, "6 000 Kč", "50 / 50", "3 000 Kč", "3 000 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 15. 7. - omítky a plotová pole", { party: "👷×3", title: "3 osoby Ivanovy party" }, "9 000 Kč", "50 / 50", "4 500 Kč", "4 500 Kč", { badge: "Evidováno", tone: "split", title: "Sdílená práce 50 / 50." }],
      ["👷 Práce 17. 7. - dokončení driveway zídky", { party: "👷×3", title: "3 osoby Ivanovy party" }, "9 000 Kč", "50 / 50", "4 500 Kč", "4 500 Kč", { badge: "Evidováno", tone: "split", title: "Sdílený projekt bez samostatné pohledávky." }],
    ],
    total: ["Celkem k úhradě od Loffelmanových", "", "165 182 Kč", "50 / 50 + 100 % L", "81 141 Kč", "84 041 Kč", "součet řádků bez přijatých plateb"],
    breakdown: [
      ["Materiál", "split", "📦 Materiál známý", "85 707 Kč", "Náš podíl: 42 853,50 Kč\nPodíl Lofflemanových: 42 853,50 Kč"],
      ["Práce", "split", "👷 Práce známá", "76 575 Kč", "Náš podíl: 38 287,50 Kč\nPodíl Lofflemanových: 38 287,50 Kč"],
      ["Pohledávka", "wait", "🏡 Náklady uhrazené Trantinovými za Loffelmanovy", "2 900 Kč", "Dlažba u Loffelmanových: práce 1 500 Kč + materiál 1 400 Kč. Nezvyšuje náš projekt ani sdílený projekt."],
    ],
  },
  settlementReceivable: {
    note:
      "K úhradě od Loffelmanových zahrnuje pouze jejich podíl na nákladech hrazených Trantinovými a 100 % náklady Loffelmanových hrazené Trantinovými. Nejde o celý společný základ.",
    cards: [
      ["50 / 50", "split", "🤝 Sdílené 50 / 50", "81 141 Kč", "Podíl Loffelmanových ze známého společného základu 162 282 Kč."],
      ["100 % L", "wait", "🏡 100 % Loffelmanovi, hrazeno námi", "2 900 Kč", "Dlažba u Loffelmanových: práce 1 500 Kč + materiál 1 400 Kč."],
      ["Uhrazeno", "good", "✅ Už uhrazeno Loffelmanovými", "0 Kč", "Zatím neevidujeme příchozí platbu od Loffelmanových."],
      ["K úhradě", "wait", "💸 Zbývá zaplatit nám", "84 041 Kč", "81 141 Kč ze sdílených nákladů + 2 900 Kč čistě jejich náklad."],
    ],
    formula: [
      ["Podíl Loffelmanových na sdíleném materiálu", "42 853,50 Kč"],
      ["Podíl Loffelmanových na sdílené práci", "38 287,50 Kč"],
      ["100 % náklady Loffelmanových hrazené námi", "2 900 Kč"],
      ["Platby přijaté od Loffelmanových", "0 Kč"],
    ],
    headers: ["Kategorie", "Položka", "Celkem", "K úhradě od Loffelmanových", "Stav"],
    rows: [
      ["Sdílený materiál 50 / 50", "WPC materiál", "37 669 Kč", "18 834,50 Kč", "✅ zaplaceno námi"],
      ["Sdílený materiál 50 / 50", "Driveway plotové pole", "14 721 Kč", "7 360,50 Kč", "✅ zaplaceno námi"],
      ["Sdílený materiál 50 / 50", "Ztracené bednění a beton", "12 282 Kč", "6 141 Kč", "✅ zaplaceno námi"],
      ["Sdílený materiál 50 / 50", "OBI materiál k přepažení", "12 964 Kč", "6 482 Kč", "✅ zaplaceno námi"],
      ["Sdílený materiál 50 / 50", "Omítka, stříšky a lišty", "7 639 Kč", "3 819,50 Kč", { badge: "Účtenka ↗", tone: "good", title: "Zaplaceno námi. Otevřít účtenku IMG_8601.JPG.", href: "assets/receipts/IMG_8601.JPG" }],
      ["Sdílený materiál 50 / 50", "T+L doplňková účtenka", "432 Kč", "216 Kč", { badge: "Účtenka ↗", tone: "good", title: "Evidováno. Otevřít účtenku IMG_8603.JPG.", href: "assets/receipts/IMG_8603.JPG" }],
      ["Sdílená práce 50 / 50", "Sdílená práce do 17. 7.", "76 575 Kč", "38 287,50 Kč", "✅ evidováno námi"],
      ["100 % Loffelmanovi", "🏡 Pokládka dlažby u Löfflemanů", "1 500 Kč", "1 500 Kč", "✅ zaplaceno Trantinovými"],
      ["100 % Loffelmanovi", "Materiál dlažby Loffelmanových cca 2 m²", "1 400 Kč", "1 400 Kč", "✅ hrazeno Trantinovými"],
      ["Platby", "Uhrazeno Loffelmanovými", "0 Kč", "-0 Kč", "⏳ čeká na úhradu"],
    ],
    total: ["K úhradě od Loffelmanových", "", "165 182 Kč", "84 041 Kč", "bez přijatých plateb"],
  },
  projects: [
    ["🧱 Ploty a zeď", ["✅ Vybráno", "✅ Objednáno", "✅ Zaplaceno", "✅ Dovezeno", "✅ Jižní plot dokončen bez podhrabovek", "✅ Východní plot - stržení původního plotu", "✅ Východní plot - řezání původní podezdívky", "✅ Východní plot - vrty pro sloupky", "✅ Východní plot - betonování sloupků", "✅ Východní plot - montáž plotových panelů", "✅ Východní plot - montáž podhrabových desek", "✅ Podhrabové desky a příslušenství dle účtenky 1 859 Kč", "✅ Kompletní dokončení východního plotu 4. 7. 2026"], "Hotovo", "good"],
    ["🚗 Driveway zídka", ["✅ Výkop základů 30. 6.", "✅ Práce 1. 7. - 75 % dne jako společný projekt", "✅ Pokračování realizace 2. 7. celou partou", "✅ Armovací stěrka", "✅ Příprava na finální omítnutí", "✅ Nalepeny stříšky", "✅ Penetrace pod finální silikonovou omítku", "✅ Omítka / dokončovací práce probíhaly do 15. 7.", "✅ Materiál Mistral a navazující materiál zaevidován jako sdílený", "✅ Dokončovací práce 17. 7. převážně na straně Loffelmanových", "✅ Projekt kompletně dokončen 17. 7. 2026", "🤝 Dělení společné práce a materiálu 50 / 50 s Lofflemanovými"], "Hotovo", "good"],
    ["🪵 Západní zídka pod WPC", ["✅ ROJA WPC desky a sloupky dorazily", "✅ WPC desky nahozeny", "✅ Podezdívka / ztracené bednění proběhlo", "✅ Armovací stěrka podezdívky pod WPC", "✅ Příprava na finální omítnutí", "✅ Nalepeny stříšky", "✅ Penetrace", "✅ Řezání stříšek", "✅ Omítka / dokončovací práce probíhaly do 15. 7.", "✅ Materiál zaevidován jako sdílený", "✅ OBI účtenky za beton a bednění zaevidovány", "✅ Projekt dokončen v rámci společných prací 17. 7. 2026"], "Hotovo", "good"],
    ["🤝 Společné práce s Löffelmanovými", ["✅ Driveway zídka dokončena", "✅ Západní zídka pod WPC dokončena", "✅ Sdílený materiál zaevidován", "✅ Sdílená práce zaevidována do 17. 7.", "✅ Celý společný projekt dokončen 17. 7. 2026", "🔒 Další práce probíhají výhradně na našem pozemku"], "Dokončeno", "good"],
    ["🪵 Pergola", ["✅ Rozpočet pergoly schválen: 207 000 Kč", "✅ Patky hotové", "⏳ Čeká termín realizace", "⏳ Navazující práce budou doplněny podle realizace"], "Čeká termín", "wait"],
    ["🌳 Zahradní domek", ["⏳ Projekt plánován", "🪨 Dlažba pod zahradní domek (cca 26 m²)", "⏳ Odhad nákladu: 18 200 Kč", "⏳ Realizace bude navázaná na finální umístění domku"], "Plánováno", "wait"],
    ["⚡ Rozvody elektřiny", ["✅ Projekt zahájen 17. 7. 2026", "✅ Vykopána první elektrotrasa směrem k východnímu plotu", "✅ Výkop směrem k východnímu plotu", "✅ 21. 7. pokračování výkopů elektroinstalace", "✅ 21. 7. pokládka husích krků", "⏳ Další etapy budou navazovat", "Poznámka: Kornhauser bez kolize, 380 V v rozvaděči, řešit s tátou zachování 11 kW nabíjení."], "Probíhá", "wait"],
    ["♨️ Vířivka", ["✅ Projekt zahájen 21. 7. 2026", "✅ Zahájena příprava terénu", "✅ Terénní úpravy pro budoucí umístění vířivky", "✅ Výkop pro štěrkové lože", "✅ Příprava plochy pro budoucí dlažbu pod vířivkou", "✅ Pokračování výkopů", "✅ Odvoz zeminy", "✅ Manipulace s dlažbou - nakládka a vykládka", "✅ Dlažba BAUHAUS pořízena a uhrazena: 20 189,40 Kč", "✅ 3. 8. pokračování výkopových prací pod budoucí vířivkou", "✅ 3. 8. navezení a rozprostření štěrku 0/32", "✅ 3. 8. příprava podkladu pro následné hutnění", "✅ Štěrk 0/32 zaevidován jako 100 % náš materiál: 4 900 Kč", "⏳ Navázat hutněním podkladu a další vrstvou podle technického plánu"], "Probíhá", "wait"],
    ["🪨 Výkopové práce pod zpevněné plochy", ["📐 Vířivka + terasa: 6,5 × 3,5 m = 22,75 m²", "📦 Vířivka + terasa: štěrk 0/32 při 20 cm = 4,55 m³", "📦 Vířivka + terasa: vyrovnávací vrstva 4/8 při 3 cm = 0,68 m³", "📐 Domek + pergola + navazující dlažba: 5,0 × 7,7 m = 38,50 m²", "📦 Domek + pergola: štěrk 0/32 při 20 cm = 7,70 m³", "📦 Domek + pergola: vyrovnávací vrstva 4/8 při 3 cm = 1,16 m³", "Σ Celková plocha zpevněných ploch: 61,25 m²", "Σ Štěrk 0/32 potřeba: 12,25 m³; doporučená objednávka 12,5–13 m³; orientačně 24–26 tun", "Σ Vyrovnávací vrstva 4/8 potřeba: 1,84 m³; doporučená objednávka cca 2 m³; orientačně cca 3 tuny", "📌 Hodnoty jsou technické parametry projektu, nikoliv již objednané množství", "✅ První evidovaný materiál: štěrk 0/32 za 4 900 Kč pro vířivku / zpevněné plochy", "✅ 6. 8. tvorba obrubníkových základů"], "Probíhá", "wait"],
    ["🏊 Bazén", "Čeká budget a finální plán."],
    ["🧱 Zábradlí", ["✅ Realizace dokončena", "✅ Namontováno", "✅ Uhrazeno", "✅ Projekt uzavřen", "🔒 100 % soukromý náklad, mimo sdílené vyúčtování"], "Dokončeno", "good"],
    ["🪞 Zrcadla", ["✅ Cena doplněna: 10 348 Kč", "✅ Výška umístění schválena", "✅ Montáž dokončena", "✅ Projekt dokončen 1. 7. 2026"], "Dokončeno", "good"],
    ["🧱 Tapety", ["✅ Tapeta - materiál pořízen / uhrazeno: 6 000 Kč", "✅ Práce 1. 7. - 25 % dne", "✅ Tapeta v dětském pokoji hotová", "✅ Tapeta v ložnici hotová", "✅ Projekt Tapety dokončen 8. 7. 2026"], "Hotovo", "good"],
    ["🏡 Projekt Löffelmanových", ["✅ Pokládka dlažby", "✅ Plocha cca 2 m²", "✅ Práce 2 hodiny", "✅ Hodnota práce 1 500 Kč", "✅ Materiál dlažby 1 400 Kč", "✅ Uhrazeno Trantinovými", "📌 Pohledávka za Loffelmanovými: 2 900 Kč", "🔒 Mimo náš projekt i mimo sdílený projekt 50 / 50"], "Pohledávka", "wait"],
    ["💡 Osvětlení", ["✅ Instalace závěsného světla BOMMA - kuchyně", "✅ Instalace světla - šatna", "⏳ Světlo - chodba 2NP", "⏳ Dodělat LED track - chodba 1NP"], "Probíhá", "wait"],
  ],
  plan: [
    {
      title: "🧱 Ploty",
      items: [
        ["ploty-vybrany", "Ploty vybrány", true],
        ["ploty-objednany", "Ploty objednány", true],
        ["ploty-zaplaceny", "Ploty zaplaceny", true],
        ["ploty-dovezeny", "Ploty a podhrabovky dovezeny", true],
        ["jizni-plot-hotov", "Jižní plot dokončen bez podhrabovek", true],
        ["vychodni-plot-strzeni", "Stržení původního plotu", true],
        ["vychodni-plot-rezani-podezdivky", "Řezání původní podezdívky", true],
        ["vychodni-plot-vrty", "Vrty pro sloupky", true],
        ["vychodni-plot-betonaz-sloupku", "Betonování sloupků", true],
        ["vychodni-plot-montaz-panelu", "Montáž plotových panelů", true],
        ["vychodni-plot-podhrabove-desky", "Montáž podhrabových desek", true],
        ["vychodni-plot-podhrabovky-uctenka", "Podhrabové desky a příslušenství dle účtenky 1 859 Kč", true],
        ["vychodni-plot-finalni-dokonceni", "Kompletní dokončení východního plotu 4. 7. 2026", true],
      ],
    },
    {
      title: "🪵 Západní zídka pod WPC",
      items: [
        ["roja-dorazila", "ROJA WPC materiál dorazil", true],
        ["wpc-nahozeny", "WPC desky nahozeny", true],
        ["ztracene-bedneni", "Ztracené bednění / podezdívka proběhla", true],
        ["armovaci-sterka-wpc-7-7", "Armovací stěrka podezdívky pod WPC", true],
        ["priprava-omitka-wpc-7-7", "Příprava na finální omítnutí", true],
        ["strisky-wpc-11-7", "Nalepeny stříšky", true],
        ["penetrace-wpc-11-7", "Penetrace", true],
        ["rezani-strisek-wpc-11-7", "Řezání stříšek", true],
        ["omitka-prubeh-15-7", "Omítka / dokončovací práce probíhaly do 15. 7.", true],
        ["omitka-material-tl-15-7", "Mistral a navazující materiál zaevidován jako sdílený", true],
        ["wpc-zapadni-zidka-hotovo-17-7", "Západní zídka pod WPC dokončena 17. 7. 2026", true],
      ],
    },
    {
      title: "🤝 Vyúčtování",
      items: [
        ["podpis-sousedky-plot", "Podpis sousedky k výměně plotu a podhrabovkám máme", true],
        ["prace-23-sdilena", "Práce 23. 6. sdílená 50 % dne", true],
        ["prace-24-sdilena", "Práce 24. 6. sdílená 75 % dne", true],
        ["prace-25-sdilena", "Práce 25. 6. sdílená 75 % dne", true],
        ["prace-26-sdilena", "Práce 26. 6. sdílená 50 % dne", true],
        ["prace-29-sdilena", "Práce 29. 6. sdílená 20 % dne", true],
        ["prace-30-6-sdilena", "Práce 30. 6. driveway zídka sdílená 100 % dne", true],
        ["prace-1-7-sdilena", "Práce 1. 7. driveway zídka sdílená 75 % dne", true],
        ["prace-2-7-sdilena", "Práce 2. 7. driveway zídka sdílená 100 % dne", true],
        ["prace-7-7-sdilena", "Práce 7. 7. armovací stěrka a příprava na omítku sdílená 100 % dne", true],
        ["prace-8-7-sdilena", "Práce 8. 7. společná zídka 1,5 h sdílená 50 / 50", true],
        ["prace-11-7-sdilena", "Práce 11. 7. stříšky a penetrace zídek sdílená 100 % dne", true],
        ["prace-15-7-sdilena", "Práce 15. 7. omítky a plotová pole sdílená 100 % dne", true],
        ["prace-17-7-sdilena", "Práce 17. 7. dokončení driveway zídky sdílená 100 % dne", true],
        ["spolecny-projekt-dokoncen-17-7", "Společný projekt s Loffelmanovými dokončen 17. 7. 2026", true],
        ["obi-uctenky-sdilene", "OBI účtenky za beton, bednění, roxor a klíny zaevidovány", true],
        ["material-omitka-listy-15-7", "T+L účtenky za omítku, stříšky a lišty za 7 639 Kč zaevidovány 50 / 50", true],
        ["obi-nesdilene-mimo-sdileni", "OBI nesdílené účtenky za 3 860 Kč vyjmuty ze sdíleného vyúčtování", true],
        ["dlazba-sousede-8-7", "Dlažba u Loffelmanových cca 2 m² / 2 h zaevidována mimo náš i sdílený rozpočet", true],
      ],
    },
    {
      title: "🧱 Zábradlí",
      items: [
        ["zabradli-realizace", "Realizace dokončena", true],
        ["zabradli-montaz", "Zábradlí namontováno", true],
        ["zabradli-uhrazeno", "Faktura uhrazena / zařazena mezi potvrzené náklady", true],
        ["zabradli-uzavreno", "Projekt uzavřen jako 100 % náš náklad", true],
      ],
    },
    {
      title: "🌳 Zahradní domek",
      items: [
        ["domek-dlazba-plan", "Dlažba pod zahradní domek (cca 26 m²) naplánována", false],
        ["domek-dlazba-termin", "Doplnit termín realizace dlažby pod zahradní domek", false],
      ],
    },
    {
      title: "🪞 Zrcadla",
      items: [
        ["zrcadla-cena", "Doplnit cenu", true],
        ["zrcadla-vyska-lucie", "Schválit výšku umístění s Lucií", true],
        ["zrcadla-montaz", "Montáž", true],
      ],
    },
    {
      title: "🧱 Tapety",
      items: [
        ["tapety-material", "Tapeta - materiál pořízen / uhrazeno: 6 000 Kč", true],
        ["tapety-prace-1-7", "Práce na tapetách 1. 7. - 25 % dne", true],
        ["tapety-detsky-pokoj", "Tapeta v dětském pokoji hotová", true],
        ["tapety-loznice", "Tapeta v ložnici hotová", true],
        ["tapety-dokonceno-8-7", "Projekt Tapety dokončen 8. 7. 2026", true],
      ],
    },
    {
      title: "⚡ Rozvody elektřiny",
      items: [
        ["elektro-start-17-7", "Projekt Rozvody elektřiny zahájen 17. 7. 2026", true],
        ["elektro-prvni-trasa", "Vykopána první elektrotrasa směrem k východnímu plotu", true],
        ["elektro-vykopy-21-7", "Pokračování výkopů elektroinstalace 21. 7.", true],
        ["elektro-husi-krky-21-7", "Pokládka husích krků 21. 7.", true],
        ["elektro-dalsi-etapy", "Navázat další etapou rozvodů elektřiny", false],
      ],
    },
    {
      title: "♨️ Vířivka",
      items: [
        ["virivka-start-21-7", "Projekt Vířivka zahájen 21. 7. 2026", true],
        ["virivka-priprava-terenu-21-7", "Zahájena příprava terénu", true],
        ["virivka-terenni-upravy-21-7", "Terénní úpravy pro budoucí umístění vířivky", true],
        ["virivka-sterkove-loze-25-7", "Výkop pro štěrkové lože", true],
        ["virivka-plocha-dlazba-25-7", "Příprava plochy pro budoucí dlažbu pod vířivkou", true],
        ["virivka-pokracovani-vykopu-27-7", "Pokračování výkopů", true],
        ["virivka-odvoz-zeminy-27-7", "Odvoz zeminy", true],
        ["virivka-dlazba-manipulace-27-7", "Manipulace s dlažbou - nakládka a vykládka", true],
        ["virivka-vykopy-3-8", "3. 8. pokračování výkopových prací pod budoucí vířivkou", true],
        ["virivka-sterk-032-3-8", "Navezení a rozprostření štěrku 0/32", true],
        ["virivka-hutneni-priprava-3-8", "Příprava podkladu pro následné hutnění", true],
        ["virivka-sterk-material-3-8", "Štěrk 0/32 zaevidován jako materiál: 4 900 Kč", true],
        ["virivka-navazat-podklad", "Navázat hutněním podkladu a další vrstvou podle technického plánu", false],
      ],
    },
    {
      title: "🪨 Výkopové práce pod zpevněné plochy",
      items: [
        ["zpevnene-virivka-terasa-plocha", "Vířivka + terasa: 6,5 × 3,5 m = 22,75 m²", true],
        ["zpevnene-virivka-sterk-032", "Vířivka + terasa: štěrk 0/32 při 20 cm = 4,55 m³", true],
        ["zpevnene-virivka-vrstva-48", "Vířivka + terasa: vrstva 4/8 při 3 cm = 0,68 m³", true],
        ["zpevnene-domek-pergola-plocha", "Domek + pergola + navazující dlažba: 5,0 × 7,7 m = 38,50 m²", true],
        ["zpevnene-domek-pergola-sterk-032", "Domek + pergola: štěrk 0/32 při 20 cm = 7,70 m³", true],
        ["zpevnene-domek-pergola-vrstva-48", "Domek + pergola: vrstva 4/8 při 3 cm = 1,16 m³", true],
        ["zpevnene-celkova-plocha", "Celková plocha zpevněných ploch: 61,25 m²", true],
        ["zpevnene-sterk-objednavka", "Štěrk 0/32: potřeba 12,25 m³, doporučená objednávka 12,5–13 m³, orientačně 24–26 tun", true],
        ["zpevnene-vrstva-48-objednavka", "Vrstva 4/8: potřeba 1,84 m³, doporučená objednávka cca 2 m³, orientačně cca 3 tuny", true],
        ["zpevnene-parametry-neobjednano", "Hodnoty jsou technické parametry projektu, nikoliv již objednané množství", true],
        ["zpevnene-obrubnikove-zaklady-6-8", "6. 8. tvorba obrubníkových základů", true],
      ],
    },
    {
      title: "💡 Osvětlení",
      items: [
        ["osvetleni-bomma-kuchyne-25-7", "Instalace závěsného světla BOMMA - kuchyně", true],
        ["osvetleni-satna-27-7", "Instalace světla - šatna", true],
        ["osvetleni-chodba-2np", "Namontovat světlo v chodbě 2NP", false],
        ["osvetleni-led-track-1np", "Dokončit LED track v chodbě 1NP", false],
      ],
    },
  ],
  electricity: [
    ["🔨 Probíhá", "wait", "Rozvody elektřiny", "Projekt zahájen 17. 7. 2026. Dne 21. 7. pokračovaly výkopy elektroinstalace a pokládka husích krků."],
    ["✅ Uzavřeno", "good", "Hlavní kabel", "Kornhauser kontaktován. Kabel vede u souseda a není v kolizi."],
    ["✅ 380 V", "good", "Rozvaděč", "V hlavním rozvaděči je 380 V."],
    ["⚠️ Riziko", "risk", "Nabíjení 11 kW", "Rozvázáním 380 V pro zahradu můžeme přijít o 11 kW nabíjení."],
    ["⏳ Úkol", "wait", "Dotáhnout tátu", "Najít řešení bez ztráty 11 kW nabíjení."],
  ],
  timeline: [
    {
      date: "17. 6. 2026",
      status: "done",
      icon: "🚀",
      title: "Start stavby",
      body: "Ivanova parta zahájila práce.",
    },
    {
      date: "23. 6. 2026",
      status: "done",
      icon: "🤝",
      title: "Společný projekt",
      body: "Začala práce na zahradním přepažení s Löffelmanovými.",
    },
    {
      date: "26. 6. 2026",
      status: "done",
      icon: "🧱",
      title: "Jižní plot",
      body: "Jižní plot dokončen bez podhrabovek.",
    },
    {
      date: "26. 6. 2026",
      status: "done",
      icon: "🪜",
      title: "Zábradlí",
      body: "Zábradlí finalizováno.",
    },
    {
      date: "30. 6. 2026",
      status: "done",
      icon: "🚗",
      title: "Driveway zídka",
      body: "Zahájen výkop základů pro driveway zídku.",
    },
    {
      date: "3. 7. 2026",
      status: "done",
      icon: "🧱",
      title: "Východní plot",
      body: "Proběhly vrty, betonování a montáž plotových panelů.",
    },
    {
      date: "4. 7. 2026",
      status: "done",
      icon: "🧱",
      title: "Východní plot dokončen",
      body: "Po dokončení montáže panelů a podhrabových desek byl východní plot kompletně dokončen.",
    },
    {
      date: "4. 7. 2026",
      status: "done",
      icon: "🏠",
      title: "Tapety",
      body: "Dětský pokoj hotový, ložnice čekala na dokončení.",
    },
    {
      date: "7. 7. 2026",
      status: "done",
      icon: "🧱",
      title: "Příprava na finální omítku",
      body: "Dokončena armovací stěrka na driveway zídce i podezdívce pod WPC jako sdílená práce s Löffelmanovými.",
    },
    {
      date: "8. 7. 2026",
      status: "done",
      icon: "🏠",
      title: "Tapety dokončeny",
      body: "Po dokončení ložnice je projekt Tapety hotový. Část dne proběhla výhradně pro Löffelmanovy mimo naše a sdílené náklady.",
    },
    {
      date: "11. 7. 2026",
      status: "done",
      icon: "🧱",
      title: "Zídky připraveny na finální omítku",
      body: "Na driveway zídce i západní zídce pod WPC byly nalepeny stříšky a provedena penetrace. Obě konstrukce jsou připravené pro finální silikonovou omítku.",
    },
    {
      date: "15. 7. 2026",
      status: "done",
      icon: "🎨",
      title: "Omítky a plotová pole",
      body: "Do deníku doplněny omítkové / dokončovací práce na driveway zídce a WPC západním plotu včetně montáže plotových polí.",
    },
    {
      date: "17. 7. 2026",
      status: "done",
      icon: "⚡",
      title: "Zahájen projekt rozvodů elektřiny",
      body: "Po dokončení zídky byla vykopána první trasa elektroinstalace směrem k východnímu plotu.",
    },
    {
      date: "17. 7. 2026",
      status: "done",
      icon: "🤝",
      title: "Dokončen společný projekt s Löffelmanovými",
      body: "Byly dokončeny všechny společné stavební práce. Další práce již probíhají výhradně na našem pozemku.",
    },
    {
      date: "21. 7. 2026",
      status: "done",
      icon: "⚡",
      title: "Rozvody elektřiny pokračují",
      body: "Pokračovaly výkopy elektroinstalace a proběhla pokládka husích krků.",
    },
    {
      date: "21. 7. 2026",
      status: "done",
      icon: "♨️",
      title: "Zahájena příprava vířivky",
      body: "Proběhly terénní úpravy pro budoucí umístění vířivky.",
    },
    {
      date: "25. 7. 2026",
      status: "done",
      icon: "♨️",
      title: "Pokračuje příprava prostoru pro vířivku",
      body: "Byl proveden výkop pro štěrkové lože pod budoucí dlažbu a současně bylo dokončeno osazení závěsného světla BOMMA v kuchyni.",
    },
    {
      date: "27. 7. 2026",
      status: "done",
      icon: "♨️",
      title: "Příprava podkladu pro vířivku pokračuje",
      body: "Pokračovaly výkopové práce, odvoz zeminy i manipulace s dlažbou. Současně bylo instalováno světlo v šatně.",
    },
    {
      date: "3. 8. 2026",
      status: "done",
      icon: "♨️",
      title: "Začalo navážení štěrku pod vířivku",
      body: "Proběhly výkopové práce a první navážka štěrku 0/32 pro budoucí podklad pod vířivku.",
    },
    {
      date: "Budoucí",
      status: "planned",
      icon: "🪵",
      title: "Pergola",
      body: "Čeká termín realizace.",
    },
    {
      date: "Budoucí",
      status: "planned",
      icon: "🏠",
      title: "Zahradní domek",
      body: "Plánovaná navazující etapa.",
    },
  ],
  missing: [
    "Termín realizace pergoly.",
    "Táta: návrh elektro řešení bez ztráty 11 kW nabíjení.",
    "Doplnit termín realizace dlažby pod zahradní domek cca 26 m².",
    "Osvětlení: namontovat světlo v chodbě 2NP a dokončit LED track v chodbě 1NP.",
  ],
};
